### DISCUSSION TITLE
Lux dependencies according to weather

### DISCUSSION THREAD

**Discussion by kenai2011** [basnijholt/adaptive-lighting#1018] [Ideas]
Hi all,
i was wondering not to read anything about weather conditions?
Backround: just installed AL with 6 parallel instances (yes, many lights need different behaviour) And here in Germany we currently had many bad weather days. And everyday of darker brightness outside all the nice settngs of AL are useless.
So is there a reason why it is not possible to implement a data source (weather, lux sensor...) to overide the nice gaussian chart with current brightness?
Thanks for lighting up my world :-)
Thomas

**Comment by TimPasquini** [comment]
I'm also curious about this. It's very rainy and gray today here in NY. Given the ambient lighting outdoors, the cool blue temps I wouldn't notice on a sunny day feel harsh and off-putting.

Did you ever find or implement a solution?

**Reply by kenai2011** [reply]
Unfortunately not. Put it behind to the other Projects without a smart solution.....🥴

**Reply by TimPasquini** [reply]
Ok, I just took a crack at a solution. I use the tomorrow.io integration for my weather.

First I created a template binary sensor called "Gray weather"  with the following State template: 
`{{ states('weather.tomorrow_io_home_daily') in ['snowy-rainy', 'snowy', 'rainy', 'cloudy', 'fog', 'drizzle', 'heavy rain', 'flurries', 'heavy snow', 'thunderstorm'] }}`

Adapt the list to contain the weather triggers you want and the entity to point at your weather entity.

Then I built the following automation:

```
alias: Adaptive Lighting Weather intervention
description: ""
triggers:
  - trigger: state
    entity_id:
      - binary_sensor.gray_weather
    id: gray_on
    to: "on"
  - trigger: state
    entity_id:
      - binary_sensor.gray_weather
    id: gray_off
    to: "off"
conditions: []
actions:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - gray_on
        sequence:
          - action: adaptive_lighting.change_switch_settings
            metadata: {}
            data:
              use_defaults: current
              entity_id: switch.adaptive_lighting_dining_room
              max_color_temp: "3000"
          - action: adaptive_lighting.change_switch_settings
            metadata: {}
            data:
              use_defaults: current
              entity_id: switch.adaptive_lighting_living_room_adaptive_lighting
              max_color_temp: "3000"
      - conditions:
          - condition: trigger
            id:
              - gray_off
        sequence:
          - action: adaptive_lighting.change_switch_settings
            metadata: {}
            data:
              use_defaults: configuration
              entity_id: switch.adaptive_lighting_dining_room
          - action: adaptive_lighting.change_switch_settings
            metadata: {}
            data:
              use_defaults: configuration
              entity_id: switch.adaptive_lighting_living_room_adaptive_lighting
mode: single
```

I *just* built this so no guarantee it will work correctly as it will take a few weather changes to assess fully. You'll need to adjust the entity IDs to your match your own. You should be able to duplicate the actions in each section and then just change the entity if you want to coordinate additional adaptive light groups.
