### DISCUSSION TITLE
Adaptive Lighting not activating when take_over_control is enbled

### DISCUSSION THREAD

**Discussion by gouthamravee** [basnijholt/adaptive-lighting#1027] [Q&A]
I have two zigbee lights, `OSRAM 73742 SYLVANIA SMART+ ZigBee Adjustable White RT 5/6 Recessed` that are controlled by a Shelly i4 behind a non-smart 3 in 1 switch. The automation at the end of the post connects the shelly to the lights. 

If I toggle either lights using the wall switch adaptive lights will not respond, unless I have `take_over_control` disabled. I want this setting because I want to manually adjust the lights brightness and temperature sometimes, and I don't want AL to change the brightness and temp at those times. 

This was a recent issue, but I'm not sure if a recent HA update caused it.  

Any help would be appreciated! 

```
- id: '1669174492397'
  alias: Office Lights Toggle
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.gravee_input
    from: 'on'
    to: 'off'
    id: Gravee
  - platform: state
    entity_id:
    - binary_sensor.gravee_input
    from: 'off'
    to: 'on'
    id: Gravee
  - platform: state
    entity_id:
    - binary_sensor.user2_input
    from: 'on'
    to: 'off'
    id: User2
  - platform: state
    entity_id:
    - binary_sensor.user2_input
    from: 'off'
    to: 'on'
    id: User2
  - platform: state
    entity_id:
    - binary_sensor.office_all_lights
    from: 'on'
    to: 'off'
    id: All
  - platform: state
    entity_id:
    - binary_sensor.office_all_lights
    from: 'off'
    to: 'on'
    id: All
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id:
        - Gravee
      sequence:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.office_gravee
    - conditions:
      - condition: trigger
        id:
        - User2
      sequence:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.office_user2
    - conditions:
      - condition: trigger
        id:
        - All
      sequence:
      - service: light.toggle
        metadata: {}
        data: {}
        target:
          entity_id: light.office_zigbee_lights
  mode: queued
  max: 10
```
