### DISCUSSION TITLE
Setting brightness_mode_time properties in automation

### DISCUSSION THREAD

**Discussion by nexusuk** [basnijholt/adaptive-lighting#1071] [Q&A]
Is it possible to set/modify the brightness_mode_time_dark and brightness_mode_time_light property values using an automation?

I originally set up my config in summer and everything was fine but the later in the year it gets the less light the room receives from the sun - this means that, for a specific time of day, the brightness settings that were fine in summer leave everyone sitting in near darkness in winter.

I was thinking I could automate a 'compensation' cycle that would adjust the tanh curve based on the time of year but the properties don't seem to be available.

**Comment by djurny** [comment]
Hi there,
It seems you actually can, but I do not know if the changed settings will take effect or not - it's worth to try out I guess?

You can call the following action/service from HASS developer tools `ACTIONS` tab:
```
action: adaptive_lighting.change_switch_settings
data:
  entity_id: switch.adaptive_lighting_<name>
  brightness_mode_time_dark: 600
  brightness_mode_time_light: 2800
```
These variables do not show up in GUI mode, but you can enter them when in YAML mode. A quick check before/after in the `STATES` tab shows that for `switch.adaptive_lighting_<name>` the values had been picked up. But again, not sure if AL uses these new values or not.

Groetjes,
