### DISCUSSION TITLE
Adaptive lighting seems to do nothing.

### DISCUSSION THREAD

**Discussion by clinta** [basnijholt/adaptive-lighting#414] [Q&A]
I'm at a loss here. I installed version 1.4.1 via HACS, added the integration in settings, configured everything via the front-end, and even enabled debug logging via the front-end. But adaptive lighting isn't doing anything. Despite debug logging being enabled, nothing is logged except the integration being loaded. Even when changing settings, turning on and off the adaptive lighting entity, or calling the `adaptive_lighting.apply` service, nothing is logged at all.

![image](https://user-images.githubusercontent.com/3177437/209456144-ad6eb67d-2b37-407a-a99d-309a0bc8ffb7.png)

If I turn my light off, then call this service

```yaml
service: adaptive_lighting.apply
data:
  entity_id: switch.adaptive_lighting_office_light
  transition: 1
  adapt_brightness: true
  adapt_color: true
  turn_on_lights: true
```

The light will turn on, but no changes to brightness or temperature are made.

I can see the brightness that it should be, via the attributes in the adaptive lighting entity, but the brightness on the light itself is never changed.

![image](https://user-images.githubusercontent.com/3177437/209456121-a6d3dedb-193e-4d5c-a41e-200e2a2adf5f.png)
