### DISCUSSION TITLE
Re-enabling Adaptive Lighting

### DISCUSSION THREAD

**Discussion by drguitarum2005** [basnijholt/adaptive-lighting#438] [Q&A]
I have adaptive lighting working well on about 8 lights. I have another automation that temporarily takes over control of 3 lights and then finishes its run. I don't want to make a separate Adaptive Lighting group for these and disable take_over_control as I want manual light switch presses to take over control as expected. After my other automation is done, is there a way to "re-enable" Adaptive Lighting for that group or something along those lines so they will continue to DIM with everything else even if the automation runs a few times throughout the day? Thanks!

**Comment by th3w1zard1** [comment]
Yes, just use `adaptive-lighting.set_manual_control()` like so:

```
service: adaptive_lighting.set_manual_control
data:
  entity_id: switch.adaptive_lighting_your_adapt_switch_name_here
  lights:
   - light.light1
   - light.light2
  manual_control: false
```

To completely reset everything just toggle the main adapt switch off and on
