### DISCUSSION TITLE
Is it possible to define multiple Adaptive Lighting instances in YAML?

### DISCUSSION THREAD

**Discussion by Sprakle** [basnijholt/adaptive-lighting#444] [Q&A] [answered]
I tried to define two separate AL instances in my `configuration.yaml` file like so:

```yaml

adaptive_lighting:
  name: "Office Adaptive Lights"
  min_color_temp: 2500
  max_color_temp: 3800
  max_sunrise_time: "07:00:00"
  min_sunset_time: "20:00:00"
  detect_non_ha_changes: true
  lights:
    - light.office_lights

adaptive_lighting:
  name: "Main Adaptive Lights"
  min_color_temp: 2500
  max_color_temp: 3800
  max_sunrise_time: "07:00:00"
  min_sunset_time: "20:00:00"
  detect_non_ha_changes: true
  lights:
    - light.main_lights
```

But only one instance shows up in HA:
<img width="1695" alt="Screenshot 2023-03-13 at 10 35 41 PM" src="https://user-images.githubusercontent.com/3256740/224906502-aa559bc9-3bc9-4e75-8243-fa6d0bb14bb1.png">

**Comment by th3w1zard1** [comment, marked as answer]
You definitely can and I highly recommend you do so!
Your syntax is incorrect, here's my yaml file.
```
adaptive_lighting:
  - name: "al_bedroom_ceilingfan_lights"
    lights: light.bedroom_ceilingfan_lights
    prefer_rgb_color: false
    transition: 120
    initial_transition: 120
    interval: 90
    sleep_transition: 45
    min_brightness: 35
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 5500
    sleep_brightness: 1
    sleep_color_temp: 1000
    take_over_control: true
    detect_non_ha_changes: true
    only_once: false
  - name: "al_den_ceilingfan_lights"
    lights: light.den_ceilingfan_lights
    prefer_rgb_color: false
    transition: 45
    sleep_transition: 45
    initial_transition: 120
    interval: 44
    min_brightness: 35
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 5500
    sleep_brightness: 1
    sleep_color_temp: 1000
    take_over_control: true
    detect_non_ha_changes: true
    only_once: false
    #max_adapt_attempts: 5
  - name: "al_linkind_dimmer_bulb"
    lights: light.linkind_dimmer_bulb
    prefer_rgb_color: false
    transition: 45
    initial_transition: 120
    interval: 90
    min_brightness: 35
    max_brightness: 100
    sleep_brightness: 1
    take_over_control: true
    detect_non_ha_changes: true
    only_once: false
    #max_adapt_attempts: asdf
  - name: "al_shellyrgbw2_ddcc57"
    lights: light.shellyrgbw2_ddcc57
    prefer_rgb_color: true
    transition: 45
    initial_transition: 120
    interval: 90
    min_brightness: 35
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 5500
    sleep_brightness: 1
    sleep_color_temp: 1000
    take_over_control: true
    detect_non_ha_changes: true
    only_once: false
  - name: "al_entrance_leds"
    lights: light.entrance_leds
    prefer_rgb_color: false
    transition: 0
    initial_transition: 0
    interval: 90
    min_brightness: 45
    max_brightness: 100
    min_color_temp: 2000
    max_color_temp: 5500
    sleep_brightness: 1
    sleep_color_temp: 1000
    take_over_control: true
    detect_non_ha_changes: true
    only_once: false
```
