### DISCUSSION TITLE
Getting more information why manual control was fired

### DISCUSSION THREAD

**Discussion by airbone42** [basnijholt/adaptive-lighting#456] [Q&A]
I have the issue that the manual control event is fired even when there was no obvious change. I logged these events to find out what is causing this, but the event information is very limited:

```  
  id: '0'
  idx: '0'
  alias: null
  platform: event
  event:
    event_type: adaptive_lighting.manual_control
    data:
      entity_id: light.buro_panel_1
      switch: switch.adaptive_lighting_adaptive_lighting_panel_1
    origin: LOCAL
    time_fired: '2022-12-12T19:03:42.525042+00:00'
    context:
      id: adapt_lgt:b'R3Id':interval:b'pa'
      parent_id: null
      user_id: null
  description: event 'adaptive_lighting.manual_control'
```

Is there any way to get more information why this was fired?

**Comment by th3w1zard1** [comment]
Yes, simply follow the instructions From the readme:

> Please enable debug logging by putting this in configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.adaptive_lighting: debug
```

We'd also need your adaptive-lighting config (listed on the integrations page) to help you debug this further.
