### DISCUSSION TITLE
How to post your Adaptive Lighting Configuration

### DISCUSSION THREAD

**Discussion by th3w1zard1** [basnijholt/adaptive-lighting#503] [General]
A recent version of Adaptive Lighting has included the config `include_config_in_attributes`
Just set it to true or check it in your configuration.

Another easy way to get the configuration:
```
service: adaptive_lighting.change_switch_settings
data:
  use_defaults: current
  include_config_in_attributes: true
```
After the next `interval`, the configuration will be available in **Developer Tools**
![image](https://user-images.githubusercontent.com/2219836/229383888-58109110-65b6-4e98-95c5-70de51caf4c2.png)
