### DISCUSSION TITLE
Remove duplicate code in YAML

### DISCUSSION THREAD

**Discussion by Jleagle** [basnijholt/adaptive-lighting#774] [Q&A] [answered]
I have all my configs in YAML (https://github.com/Jleagle/smart-home/blob/main/hass/config.yml#L81) and they are all the same except for the min_brightness.

Is there a way i can set a default of some kind so i can remove the bulk of it and just set it in one place.

**Comment by basnijholt** [comment, marked as answer]
Wow, those are a lot of instances.

Unfortunately, there is no way to template this ATM.

**Reply by Jleagle** [reply]
Okay thanks.

**Reply by juhi24** [reply]
It would be cool if you could inherit defaults like:
```yaml
- name: "default"
  lights: []
  some_settings:
- name: "livingroom"
  parent: "default"
  lights:
    - light.livingroom
```
