### DISCUSSION TITLE
Is it possible to turn on prefer_rgb_color after sunset

### DISCUSSION THREAD

**Discussion by danis197** [basnijholt/adaptive-lighting#779] [Q&A] [answered]
Hey, I would like to turn on prefer_rgb_color after sunset, but i don't know how...
anyone has a solution for this?

My idea was to create a button like switch.prefer_rgb_color to easliy turn prefer_rgb_color on and off

Thanks in advance!

**Comment by basnijholt** [comment, marked as answer]
We can create an automation that changes the `prefer_rgb_color` setting of the Adaptive Lighting integration after sunset. Additionally, we can create a virtual switch that allows the user to easily toggle the `prefer_rgb_color` setting on and off.

Here's how you can achieve this:

### 1. Automation to set `prefer_rgb_color` after sunset:

```yaml
automation:
  - alias: "Set prefer_rgb_color after sunset"
    trigger:
      platform: sun
      event: sunset
    action:
      service: adaptive_lighting.change_switch_settings
      data:
        entity_id: switch.adaptive_lighting_default  # Replace with your Adaptive Lighting switch entity_id
        prefer_rgb_color: true
```

### 2. Create a virtual switch to toggle `prefer_rgb_color`:

First, create an `input_boolean` which will act as a virtual switch:

```yaml
input_boolean:
  toggle_prefer_rgb_color:
    name: "Toggle RGB Color Preference"
    initial: off
```

Then, create two automations. One will turn on `prefer_rgb_color` when the virtual switch is turned on, and the other will turn it off when the virtual switch is turned off:

```yaml
automation:
  - alias: "Turn on prefer_rgb_color with virtual switch"
    trigger:
      platform: state
      entity_id: input_boolean.toggle_prefer_rgb_color
      to: 'on'
    action:
      service: adaptive_lighting.change_switch_settings
      data:
        entity_id: switch.adaptive_lighting_default  # Replace with your Adaptive Lighting switch entity_id
        prefer_rgb_color: true

  - alias: "Turn off prefer_rgb_color with virtual switch"
    trigger:
      platform: state
      entity_id: input_boolean.toggle_prefer_rgb_color
      to: 'off'
    action:
      service: adaptive_lighting.change_switch_settings
      data:
        entity_id: switch.adaptive_lighting_default  # Replace with your Adaptive Lighting switch entity_id
        prefer_rgb_color: false
```

With these configurations, the user can easily toggle the `prefer_rgb_color` setting using the virtual switch (`input_boolean.toggle_prefer_rgb_color`). Additionally, the setting will automatically be enabled after sunset.
