### DISCUSSION TITLE
Automating sleep mode switch

### DISCUSSION THREAD

**Discussion by chrisghz** [basnijholt/adaptive-lighting#783] [Q&A] [answered]
I wouldn’t say I’m a novice with HA, but I’ve stumped myself and cannot for the life of me automate the activation and subsequent deactivation of the sleep function? 
has anyone achieves this?

**Comment by basnijholt** [comment, marked as answer]
An example that turns it on at 22:00:

```yaml
automation:
  - alias: "Turn on adaptive lighting sleep mode at 22:00"
    trigger:
      platform: time
      at: '22:00:00'
    action:
      service: switch.turn_on
      entity_id: switch.adaptive_lighting_sleep_mode_example
```
