### DISCUSSION TITLE
Regain control - brightness only

### DISCUSSION THREAD

**Discussion by CaptainN** [basnijholt/adaptive-lighting#787] [Q&A] [answered]
Hi! First, thanks for such an amazing project! Love it.

I'm currently using a fairly vanilla set up with adaptive-lighting, but I'd like to change just a few things. Specifically:
- Make it so that using my dimmer switches only disables brightness adaptation, but NOT color adaptation. So if I set my lights to bright, they'll still continue to get browner at night.
- Make it so that some lights, but not all, enter sleep mode at night.

Are these things possible with the current version?

Thanks again!

Here's my configuration:

```yaml
adaptive_lighting:
- name: "Adaptive Lighting"
  prefer_rgb_color: false
  min_brightness: 35
  max_brightness: 100
  min_color_temp: 2700
  max_color_temp: 5000
  sleep_brightness: 1
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  lights:
    - light.living_room_lights
    - light.livingroom_fan
    - light.livingroom_fan_2
    - light.livingroom_fan_3
    - light.living_room_fan_4
    - light.front_room_lamp_light
    - light.hue_ambiance_lamp_1
    - light.hue_ambiance_lamp_2
    - light.hue_ambiance_lamp_1_2
    - light.hue_ambiance_lamp_1_3
    - light.cat_room_floodlight_1
    - light.cat_room_floodlight_2
    - light.cat_room_fan_light
    - light.hallway_light
    - light.hue_color_lamp_1
    - light.garage_light
```
