### DISCUSSION TITLE
Help with adapting lifx bulbs

### DISCUSSION THREAD

**Discussion by sambarlick** [basnijholt/adaptive-lighting#890] [Q&A]
Hi,

I wonder if anyone can help.
For a while I've been having an issue with my lifx bulbs not automatically adapting. I have to manually or automate a service call to adapt them.

I have tried different combinations of the checkboxs in AL configuration UI but none seem to allow the lifx bulbs to automatically adapt. My hue and tuya lights have no issues adapting automatically just my lifx ones.

Has anyone had any similar issues with lifx?

Thanks,
Sam

**Comment by Djelibeybi** [comment]
My LIFX bulbs are working fine with Adaptive Lighting. Does manually calling the `light.turn_on` service work?

Having said that, I generally recommend configuring Adaptive Lighting without any actual physical devices then creating two template entities via the Helpers page to extract the current colour temperature in kelvin and the current brightness from the Adaptive Lighting switch. 

You can then use the values from those sensors in an automation that runs every 5 minutes that calls `lifx.set_state` instead which will transform the bulbs whether they're on or not. For this to work, you need to ensure any `light.turn_on` calls you make with any other automation, e.g. triggered by a motion sensor or smart button/switch, doesn't have any values for those same attributes. 

The template for colour temperature would look like this:

```jinja
{{ state_attr("switch.adaptive_lighting_reference", "color_temp_kelvin") }}
```

And the brighess would look like this:

```jinja
{{ state_attr("switch.adaptive_lighting_reference", "brightness_pct") }}
```

The service call would then look something like this:

```yaml
service: lifx.set_state
target:
  entity_id: light.lifx_bulb
data:
  transition: 45
  brightness_pct: '{{ states("sensor.adaptive_lighting_brightness") }}'
  color_temp_kelvin: '{{ states("sensor.adaptive_lighting_color_temperature") }}'
```

Hope that makes sense/helps. :)
