### DISCUSSION TITLE
Delay before light is marked as manually_controlled

### DISCUSSION THREAD

**Discussion by DiederikvandenB** [basnijholt/adaptive-lighting#909] [Q&A]
I am developing a custom lovelace card for AL. In my current setup, I have one light (`light.bedroom_ceiling_light`) added to the integration. The config:

```
adaptive_lighting:
  - name: Bedroom

    lights:
      - light.bedroom_ceiling_light

    interval: 30
    transition: 60

    take_over_control: true
```

Now, with the AL switch toggled on and the light on, I send a `light.turn_on` service call to change the brightness. I am expecting either the AL switch to be *immediately* disabled, or for the specific light to be *immediately* added to the `attributes.manual_control` list.

In reality, nothing changes immediately, but after a while (maybe on the next interval?) the light is added to the `manual_control` list. I need this value to change immediately as I use these fields to show an (in-)active state for certain buttons in my lovelace card.

Of course, I can easily make an automation which manually adds the light to the `manual_control` list, but I thought this was already implemented in this integration. Long story short: is this a config/user error on my side, or does my use case indeed call for the manual service call (`adaptive_lighting.set_manual_control`)?
