### ISSUE TITLE
[adapt_brightness] is an invalid option for [adaptive_lighting]

### ISSUE THREAD

**Issue by spencerthayer** [basnijholt/adaptive-lighting#101]
I am getting the following error `Invalid config for [adaptive_lighting]: [adapt_brightness] is an invalid option for [adaptive_lighting]. Check: adaptive_lighting->adaptive_lighting->0->adapt_brightness. (See /config/configuration.yaml)`. Below is my configuration.

```YAML
adaptive_lighting:
  - name: "Circadian Livingroom"
    lights:
      - light.wiz_4bf2c0
      - light.wiz_4bf2da
      - light.wiz_45b41e
      - light.wiz_45b430
    prefer_rgb_color: false
    initial_transition: 1
    transition: 15
    interval: 30
    adapt_brightness: no
    min_color_temp: 2600
    max_color_temp: 5600
    sleep_brightness: 10
    sleep_color_temp: 1000
    take_over_control: true
    detect_non_ha_changes: true
    only_once: false
```
