### ISSUE TITLE
Light group color temperature resolution elicits manual control event

### ISSUE THREAD

**Issue by djurny** [basnijholt/adaptive-lighting#1164]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [x] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [x] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#sos-troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

```
- name: Work room
  lights:
    - light.work_room_desk
  min_brightness: 50
  interval: 90
  transition: 10
  initial_transition: 2
  max_brightness: 100
  min_color_temp: 2700
  max_color_temp: 4000
  prefer_rgb_color: False
  sleep_brightness: 1
  sleep_rgb_or_color_temp: color_temp
  sleep_color_temp: 2000
  sleep_transition: 30
  transition_until_sleep: False
  min_sunrise_time: 06:15:00
  max_sunrise_time: 07:00:00
  sunset_offset: 3600
  brightness_mode: tanh
  brightness_mode_time_dark: 7200
  brightness_mode_time_light: 0
  take_over_control: True
  detect_non_ha_changes: False
  autoreset_control_seconds: 0
  only_once: False
  adapt_only_on_bare_turn_on: True
  separate_turn_on_commands: False
  send_split_delay: 0
  adapt_delay: 0
  skip_redundant_commands: True
  intercept: False
  multi_light_intercept: False
  include_config_in_attributes: True
```

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
N/A
4.  Describe the bug and how to reproduce it:
Most of my `light` groups in HASS consist of different brands and models of bulbs. e.g. Hue + WiZ + Ikea. 
These groups cannot follow the exact color temperature as AL wants to set them at. The `color_temp` set will not match the `color_temp` the group reports back. 
![image](https://github.com/user-attachments/assets/623b4b9b-54a0-4cfb-9236-7b306c991f10)
However, the `mired` value set _does_ match the `mired` value reported by the group.
This results in the AL instance to think the `light` is manually controlled, when in fact, it is not.
If AL would check on `mired` mismatch instead of `color_temp` it will not presume the lights to be manually controlled.
https://github.com/basnijholt/adaptive-lighting/blob/9aee2349555ad25937ba3b7b614b7776e2d3bce5/custom_components/adaptive_lighting/switch.py#L755
Oddly enough, I do not see the `_LOGGER.debug("Color temperature of '%s' significantly changed from %s to %s with context.id='%s'", ...)` in my debug logging?

5. Steps to reproduce the behavior:
- Make a HASS `light` group with different brands and models of bulb. In my case 1 Hue white ambiance and 1 30W IKEA LED driver.
- Let AL control the `light` group for a while and depending on the color temperature set, the color temperature reported will not match.
- AL will fire a `manual_control` event for the instance.
