### ISSUE TITLE
Cannot enter min/max times later than 11:59:00

### ISSUE THREAD

**Issue by djurny** [basnijholt/adaptive-lighting#1184]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [x] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [x] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#sos-troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [ ] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

```
2025-03-14 14:04:33.689 ERROR (MainThread) [homeassistant.config] Invalid config for 'adaptive_lighting' at configuration.d/adaptive_lighting.yaml, line 355: Invalid time specified: 68400 for dictionary value 'adaptive_lighting->9->max_sunset_time', got 68400, please check the docs at https://github.com/basnijholt/adaptive-lighting#readme
2025-03-14 14:04:33.690 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'adaptive_lighting': Invalid config.
```

```
Invalid time specified: 68400 for dictionary value 'adaptive_lighting->9->max_sunset_time', got 68400
```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

```
- name: Sofa overhead
  lights:
    - light.sofa_overhead
  min_brightness: 1
  interval: 90
  transition: 5
  initial_transition: 2
  max_brightness: 60
  min_color_temp: 2700
  max_color_temp: 4000
  prefer_rgb_color: False
  sleep_brightness: 1
  sleep_rgb_or_color_temp: color_temp
  sleep_color_temp: 2000
  sleep_transition: 30
  transition_until_sleep: False
  min_sunrise_time: 06:15:00
  max_sunrise_time: 07:00:00
  max_sunset_time: 19:00:00
  sunset_offset: 3600
  brightness_mode: tanh
  brightness_mode_time_dark: 7200
  brightness_mode_time_light: 0
  take_over_control: True
  detect_non_ha_changes: False
  autoreset_control_seconds: 0
  only_once: False
  adapt_only_on_bare_turn_on: True
  separate_turn_on_commands: False
  send_split_delay: 0
  adapt_delay: 0
  skip_redundant_commands: True
  intercept: True
  multi_light_intercept: True
  include_config_in_attributes: True
```

3.  (If using Zigbee2MQTT), provide your configuration files (**remove all personal information before posting**):
    - `devices.yaml`
    - `groups.yaml`
    - `configuration.yaml` ⚠️; **Warning** _**REMOVE ALL of the PERSONAL INFORMATION BELOW before posting**_ ⚠️;
      - mqtt: `server`:
      - mqtt: `user`:
      - mqtt: `password`:
      - advanced: `pan_id`:
      - advanced: `network_key`:
      - anything in `log_syslog` if you use this
    - Brand and model number of problematic light(s)
```
```

4.  Describe the bug and how to reproduce it:
Not able to set a 24h time for `min`/`max` `sunrise/sunset` `time`, such as `19:00:00` or `13:00`. Tried several ways, like `19:00`, `07:00:00pm`, `07:00:00 pm`, `07:00PM`, none of the combinations seem to work. Times earlier than `12:00:00` seem to work just fine.

5. Steps to reproduce the behavior:
Add `min_sunrise_time` or `max_sunrise_time` (or the `_sunset_time` ones) to any 24h notation time after `12:00:00`. Restart HASS.
