### ISSUE TITLE
set_manual_control with nested HA light groups not working as expected

### ISSUE THREAD

**Issue by LordOfCorners** [basnijholt/adaptive-lighting#1187]
Hi! I was trying to apply `set_manual_control` to true, providing a list of my lights in my living room. I have a Home Assistant group called `living_room_lights`. This group is made up of `living_room_lamp`, and `living_room_ceiling`. `living_room_ceiling` is itself a group of `living_room_ceiling_one` and `living_room_ceiling_two` (I prefer to not group them in zigbee2mqtt because I like to be able to control individual bulbs in the fixture from HA when using RGB lighting).

```
- data:
     entity_id: switch.adaptive_lighting_living_room
     lights:
        - light.living_room_lights
     manual_control: true
  action: adaptive_lighting.set_manual_control
```

This results in `Manual control: [light.living_room_lamp]`

However, if I remove the lights argument, or if I put `living_room_ceiling_one` and `living_room_ceiling_two` in `living_room_lights` instead of `living_room_ceiling`, 

I get

```
Manual control:  [
  light.living_room_ceiling_one, 
  light.living_room_ceiling_two, 
  light.living_room_lamp
]
```

Either of those two workarounds are fine with me. Just wanted to point this out in case it hasn't been.
