### ISSUE TITLE
Light color doesn't change over time when using adaptive_lighting.apply

### ISSUE THREAD

**Issue by jarrah31** [basnijholt/adaptive-lighting#121]
My use case is to have a light that is manually turned on/off from a wall switch. When turned on, it changes to the appropriate color temperature for that time of day, and then automatically adjusts the color if left on. Brightness stays at 100% all the time.

The problem I'm having is that color isn't adjusting over time.

My yaml configuration is as follows:
```
adaptive_lighting:
- name: huelamps
  min_color_temp: 2400
  take_over_control: false
  min_brightness: 100
  initial_transition: 1
```
I set `min_brightness` to 100 to prevent the light from dimming
```
# A Xiaomi Zigbee switch turns on the light via a script
script:
  opple_famrm_3_single:
    sequence:
      - service: adaptive_lighting.apply
        entity_id: switch.adaptive_lighting_huelamps
        data:
          lights: light.family_room_lamp
          transition: 1
          turn_on_lights: true
          adapt_brightness: true
          adapt_color: true
```
I set `adapt_brightness` and `adapt_color` so that the light adjusts to the current adaptive light settings when switched on.

I see the `color_temp_mired` value within `switch.adaptive_lighting_huelamps` attribute changing over time, yet the bulb `color_temp` stays at the value it was set to when switched on:
![image](https://user-images.githubusercontent.com/3072303/119179449-d05b3180-ba66-11eb-95b8-f10c420f6074.png)
![image](https://user-images.githubusercontent.com/3072303/119179707-2af48d80-ba67-11eb-86a9-c7501569af2f.png)

As seen in the screenshots, all `adaptive_lighting` entities are on except for `switch.adaptive_lighting_adapt_brightness_huelamps` and sleep mode.

If I press the Xiaomi switch to trigger the above script whilst the light is on, it adjusts the color to the current value shown within `switch.adaptive_lighting_huelamps`.

The Integration looks like this:
![image](https://user-images.githubusercontent.com/3072303/119180581-604dab00-ba68-11eb-9ea4-54cd34a44e06.png)

I installed Adaptive Lighting via HACS and is currently on version 41d149d.
