### ISSUE TITLE
Feedback-Loop with brightness sensor

### ISSUE THREAD

**Issue by RubenKelevra** [basnijholt/adaptive-lighting#122]
It would be nice if the adaptive lighting could take a brightness sensor into account.

Placed correctly it should be possible to dim the lights automatically based on the natural lighting shining in via the windows while automatically add lighting if necessary to maintain good lighting over the day, for example in a storm/rainshower or when it gets dark early in winter.

**Comment by vring0** [comment]
This function is very lacking, you have to come up with your own crutches.

**Comment by vring0** [comment]
Any news?

**Comment by RubenKelevra** [comment]
@vring0 

I'm currently in the process of doing version 2. This will be added/fixed.

**Comment by basnijholt** [comment]
This is essentially the same request as https://github.com/basnijholt/adaptive-lighting/issues/578.

Copying my response from there:

This can be implemented using a simple automation.

Just use the `adaptive_lighting.change_switch_settings` ( https://github.com/basnijholt/adaptive-lighting#adaptive_lightingchange_switch_settings) and adjust your `max_color_temp` accordingly.

You can utilize a linear equation to adjust the `max_brightness` continuously based on the brightness sensor's reading. Here's a sample automation that linearly scales the `max_brightness` based on the readings of the `sensor.brightness`:

```yaml
automation:
  - alias: "Adjust Adaptive Lighting Brightness based on Brightness Sensor"
    trigger:
      platform: state
      entity_id: sensor.brightness
    action:
      - service: adaptive_lighting.change_switch_settings
        data_template:
          max_brightness: >
            {% set sensor_val = states('sensor.brightness')|int %}
            {% set max_brightness = 100 - sensor_val %}
            {{ [1, max_brightness, 100]|sort()[1] }}
```

Explanation:

- The automation triggers every time the state of `sensor.brightness` changes.
- The linear equation used is \( \text{max\_brightness} = 100 - \text{sensor\_value} \). This means when the brightness sensor reads a value of 0, the maximum brightness will be 100, and when the brightness sensor reads a value of 100, the maximum brightness will be 0.
- The template at the end ensures that the value stays between 1 and 100.

You can adjust the linear equation to better suit your needs.

Will close this issue because a solution exists. Thanks for your suggestion though!

**Comment by RubenKelevra** [comment]
@basnijholt I tried now half an hour to get this working and only get "Message malformed: template value should be a string for dictionary value @ data['action'][0]['data_template']", regardless what I try.

I don't think that's a user-friendly approach.

**Comment by basnijholt** [comment]
Are you talking about the automation?

**Comment by RubenKelevra** [comment]
@basnijholt wrote:
> Are you talking about the automation?

Yeah, I can't get it to work - at least not in HA version 2024.9.0b1.

Here's an example how my automation looks, without the data_template. But I can't get it to work, if I add the data_template you suggested.

```
alias: Adjust Adaptive Lighting Brightness based on Brightness Sensor - Left Room
trigger:
  - platform: state
    entity_id: sensor.brightness_left_room_illuminance_lux
action:
  - action: adaptive_lighting.change_switch_settings
    metadata: {}
    data:
      use_defaults: current
      entity_id: switch.adaptive_lighting_adapt_brightness_left_room
      max_brightness: "100"
```

**Comment by RubenKelevra** [comment]
Anyway, I tried it manually:

I've used a strong light to illuminate the room, outside of Adaptive Lighting - to simulate natural light entering a room.

Then I set the max_brightness value manually, from what the sensor reported, as you suggested.

The results suggest that this approach will lead to vastly different room brightnesses, depending on natural light present or not:

0 lux natural light: 37 lux room brightness with light on
25 lux natural light: 50 lux room brightness with light on
48 lux natural light: 62 lux room brightness with light on
69 lux natural light: 74 lux room brightness with light on


So while using your automation would reduce the energy consumption, as the lights would dim, it would leave different rooms with different amounts of artifical light at the same time of day with large differences in light level.

**Comment by RubenKelevra** [comment]
Here's the solution I came up with:

```
alias: Adjust Brightness in Left Room
description: >-
  Adjusts the brightness of lamps to achieve the target brightness in the left
  room.
trigger:
  - platform: state
    entity_id:
      - sensor.brightness_left_room_illuminance_lux
      - number.target_brightness_left_room
  - platform: state
    entity_id:
      - sensor.brightness_left_room_illuminance_lux
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - platform: state
    entity_id:
      - sensor.brightness_left_room_illuminance_lux
    for:
      hours: 0
      minutes: 1
      seconds: 30
  - platform: state
    entity_id:
      - sensor.brightness_left_room_illuminance_lux
    for:
      hours: 0
      minutes: 2
      seconds: 0
  - platform: state
    entity_id:
      - sensor.brightness_left_room_illuminance_lux
    for:
      hours: 0
      minutes: 2
      seconds: 30
  - platform: state
    entity_id:
      - sensor.brightness_left_room_illuminance_lux
    for:
      hours: 0
      minutes: 3
      seconds: 0
  - platform: state
    entity_id:
      - sensor.brightness_left_room_illuminance_lux
    for:
      hours: 0
      minutes: 3
      seconds: 30
  - platform: state
    entity_id:
      - sensor.brightness_left_room_illuminance_lux
    for:
      hours: 0
      minutes: 4
      seconds: 0
condition: []
action:
  - variables:
      current_brightness: "{{ states('sensor.brightness_left_room_illuminance_lux') | float }}"
      target_brightness: "{{ states('number.target_brightness_left_room') | float }}"
      max_ceiling_contribution: >-
        {{
        states('input_number.max_brightness_contribution_left_room_ceiling_lamps')
        | float }}
      max_spot_contribution: >-
        {{
        states('input_number.max_brightness_contribution_left_room_floodlight')
        | float }}
      ceiling_contribution_per_step: "{{ max_ceiling_contribution / 255 }}"
      spot_contribution_per_step: "{{ max_spot_contribution / 255 }}"
      required_lux: "{{ target_brightness - current_brightness }}"
      adjustment_limit: 26
      spot_lights_on: "{{ states('light.spot_lights_left_room') != 'off' }}"
      ceiling_brightness: "{{ state_attr('light.ceiling_lamps_left_room', 'brightness') | int }}"
      spot_brightness: "{{ state_attr('light.spot_lights_left_room', 'brightness') | int }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ spot_lights_on and (ceiling_brightness < 255) }}"
        sequence:
          - target:
              entity_id:
                - light.ceiling_lamps_left_room
                - light.lamp_left_room_floor_lamp
            data:
              brightness: 255
              transition: 20
            action: light.turn_on
      - conditions:
          - condition: template
            value_template: "{{ current_brightness < target_brightness }}"
        sequence:
          - variables:
              needed_ceiling_brightness: "{{ (required_lux / ceiling_contribution_per_step) | int }}"
              adjusted_ceiling_brightness: |
                {% if spot_lights_on %}
                  255
                {% else %}
                  {{ [ceiling_brightness + needed_ceiling_brightness, 255, ceiling_brightness + adjustment_limit] | min | int }}
                {% endif %}
              remaining_required_lux: >-
                {{ required_lux - (adjusted_ceiling_brightness -
                ceiling_brightness) * ceiling_contribution_per_step }}
              needed_spot_brightness: >-
                {{ (remaining_required_lux / spot_contribution_per_step) | int
                if remaining_required_lux > 0 else 0 }}
              adjusted_spot_brightness: >-
                {{ [spot_brightness + needed_spot_brightness, 255,
                spot_brightness + adjustment_limit] | min | int }}
          - target:
              entity_id:
                - light.ceiling_lamps_left_room
                - light.lamp_left_room_floor_lamp
            data:
              brightness: "{{ adjusted_ceiling_brightness }}"
              transition: 20
            action: light.turn_on
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ remaining_required_lux > 0 }}"
                sequence:
                  - target:
                      entity_id: light.spot_lights_left_room
                    data:
                      brightness: "{{ adjusted_spot_brightness }}"
                      transition: 20
                    action: light.turn_on
      - conditions:
          - condition: template
            value_template: "{{ current_brightness > target_brightness }}"
        sequence:
          - variables:
              excess_lux: "{{ current_brightness - target_brightness }}"
              needed_spot_reduction: "{{ (excess_lux / spot_contribution_per_step) | int }}"
              adjusted_spot_brightness: >-
                {{ [spot_brightness - needed_spot_reduction, 0, spot_brightness
                - adjustment_limit] | max | int }}
              spot_reduction_guarded: >-
                {{ 0 if adjusted_spot_brightness <= 3 else
                adjusted_spot_brightness }}
              remaining_excess_lux: >-
                {{ excess_lux - (spot_brightness - spot_reduction_guarded) *
                spot_contribution_per_step }}
          - target:
              entity_id: light.spot_lights_left_room
            data:
              brightness: "{{ spot_reduction_guarded }}"
              transition: 20
            action: light.turn_on
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ spot_reduction_guarded == 0 }}"
                sequence:
                  - target:
                      entity_id:
                        - light.ceiling_lamps_left_room
                        - light.lamp_left_room_floor_lamp
                    data:
                      brightness: 255
                      transition: 20
                    action: light.turn_on
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
mode: queued
max: 50
```

I don't think that's easy for the average users to do.
