### ISSUE TITLE
Expose sun position sensor

### ISSUE THREAD

**Issue by domoritz** [basnijholt/adaptive-lighting#14]
It would be awesome if the plugin exposed the sun position (between -100 and 100) similar to `sensor.circadian_values`. My use case is to show day/night as a line in my mini graph cards (similar to https://github.com/kalkih/mini-graph-card#alternate-y-axis).

**Comment by basnijholt** [comment]
You can just do this: https://github.com/basnijholt/home-assistant-config/blob/251f02def4a3d35648147b069742a748acc8265f/includes/sensors.yaml#L265-L283

```yaml
    adaptive_lighting_color_temp_mired:
      unit_of_measurement: "mired"
      value_template: >
        {{ state_attr("switch.adaptive_lighting_default", "color_temp_mired") }}
    adaptive_lighting_color_temp_kelvin:
      unit_of_measurement: "K"
      value_template: >
        {{ state_attr("switch.adaptive_lighting_default", "color_temp_kelvin") }}
    adaptive_lighting_percent:
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr("switch.adaptive_lighting_default", "percent") }}
    adaptive_lighting_brightness:
      unit_of_measurement: "%"
      value_template: >
        {{ state_attr("switch.adaptive_lighting_default", "brightness_pct") }}

```
