### ISSUE TITLE
More than 10 configurations doesn't work properly

### ISSUE THREAD

**Issue by kirbo** [basnijholt/adaptive-lighting#146]
Hi,

So, I had configured 12 Adaptive Lighting settings, such as:
```yaml
- name: "Keittiö - UFO"
  lights:
    - light.hue_lamp_ufo
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 25
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Keittiö - Spottivalo"
  lights:
    - light.keittionspotti
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 25
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Eteinen - Kattovalot"
  lights:
    - light.eteinen
    - light.hue_bulb_white_ambiance_wc_eteinen
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 15
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Makuuhuone - Kattovalo"
  lights:
    - light.hue_bulb_white_ambiance_makuuhuoneen_kattovalo
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 15
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Makuuhuone - Yövalot"
  lights:
    - light.hue_bulb_white_ambiance_kirbo_yovalo
    - light.hue_bulb_white_ambiance_milli_yovalo
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 20
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Olohuone - Kattovalo"
  lights:
    - light.hue_bulb_rgb_olohuone
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 25
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Olohuone - Makkarit"
  lights:
    - light.hue_bulb_white_ambiance_makkarit
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 15
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Kylpyhuone - Ledit"
  lights:
    - light.bathroom
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 20
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Työpöytä - Ledi"
  lights:
    - light.hue_ledstrip_tyopoyta
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 15
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Nuutin huone - Kattovalo"
  lights:
    - light.hue_bulb_rgb_nuutin_kattovalo
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 30
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Nuutin huone - Sängyn alla"
  lights:
    - light.hue_ledstrip_nuutin_huomio
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 30
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Nuutin huone - Yövalo"
  lights:
    - light.hue_ledstrip_nuutin_yovalo
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 30
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'
```

...but for both `Makuuhuone - Kattovalo` and `Makuuhuone - Yövalot` ONLY the Color Temperature worked when I switched the light on. The brightness was what ever it was last time.

Now that I changed my configurations as following:
```yaml
- name: "Keittiö - Kattovalot"
  lights:
    - light.hue_lamp_ufo
    - light.keittionspotti
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 25
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Eteinen - Kattovalot"
  lights:
    - light.eteinen
    - light.hue_bulb_white_wc_eteinen
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 15
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Makuuhuone - Valot"
  lights:
    - light.hue_bulb_white_makkarin_kattovalo
    - light.hue_bulb_white_kirbo_yovalo
    - light.hue_bulb_white_milli_yovalo
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 20
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Olohuone - Kattovalo"
  lights:
    - light.hue_bulb_rgb_olohuone
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 25
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Olohuone - Makkarit"
  lights:
    - light.hue_bulb_white_makkarit
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 15
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Kylpyhuone - Ledit"
  lights:
    - light.bathroom
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 20
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Työpöytä - Ledi"
  lights:
    - light.hue_ledstrip_tyopoyta
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 15
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Nuutin huone - Kattovalo"
  lights:
    - light.hue_bulb_rgb_nuutin_kattovalo
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 30
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Nuutin huone - Sängyn alla"
  lights:
    - light.hue_ledstrip_nuutin_huomio
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 30
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'

- name: "Nuutin huone - Yövalo"
  lights:
    - light.hue_ledstrip_nuutin_yovalo
  prefer_rgb_color: false
  transition: 30
  initial_transition: 0.25
  interval: 60
  min_brightness: 30
  sleep_brightness: 10
  sleep_color_temp: 1000
  take_over_control: true
  detect_non_ha_changes: true
  only_once: false
  sunrise_offset: '-00:30:00'
  sunset_offset: '+00:30:00'
```
...everything works. The problem is that I would've liked to have more separete configurations, instead of combining 4 of my configurations into 2 (to save space or whatever).
