### ISSUE TITLE
Bug: Scenes do not trigger manual control anymore?

### ISSUE THREAD

**Issue by flecmart** [basnijholt/adaptive-lighting#147]
Hi there,

I migrated to adaptive lighting since the circadian lighting component was not maintained anymore. I am pretty happy with the take back control features of adaptive lighting and everything was working as expected/documented so far.

Lately I noticed that my scenes that I set up in home assistant do not trigger the manual control for the lights anymore even though the lights were in state on before. So the scenes will now be overwritten by adaptive lighting during the next interval.

Unfortunately I am not sure since when this behavior occurs but I am sure that my scenes put the lights in the manaul_control list of the adaptive lighting switch before.

Example of my config:

configuration.yaml:

```
adaptive_lighting:
  - name: living
    lights:
      - light.buro
      - light.wohnzimmer
    take_over_control: true
    detect_non_ha_changes: true


light:
  - platform: mqtt
    schema: json
    name: Wohnzimmer
    command_topic: 'zigbee2mqtt/light_wohnzimmer/set'
    state_topic: 'zigbee2mqtt/light_wohnzimmer'
    brightness: true
    color_temp: true
    rgb: true
    qos: 1
  - platform: mqtt
    schema: json
    name: Büro
    command_topic: 'zigbee2mqtt/light_buro/set'
    state_topic: 'zigbee2mqtt/light_buro'
    brightness: true
    color_temp: true
    rgb: true
    qos: 1
```

example scene from scenes.yaml:

```
- name: Büro scene
  entities:
    light.0x0..._light_buro_schreibtisch:
      state: on
      brightness: 254
      xy_color: [0.45,0.407]
      transition: 2
    light.0x0..._light_buro_regal:
      state: on
      brightness: 254
      xy_color: [0.31,0.201]
      transition: 2
```

The light groups  are zigbee groups in zigbee2mqtt and the lights referenced in `scenes.yaml` are singe lights that are part of this group. Calling the scene changes attributes in multiple lights of the group and therefore also the group attributes are changing (e.g. average brightness or color).

Does anyone have an idea where this could come from? Sure I could call set_manual control manually and wrap my scenes in scripts but I would rather find a general fix.

Thanks and best regards,
Martin
