### ISSUE TITLE
reset manual_control is never working because bug in condition value?

### ISSUE THREAD

**Issue by JDFS404** [basnijholt/adaptive-lighting#172]
#### Version information:
Latest

#### Description:
I cannot get reset manual_control to work, it's not grabbing the code correctly it seems. Let me show you what I tried doing in the developer tool. I have multiple switches, but for this example I use ```switch.adaptive_lighting_bedroom``` with ```light.desk```.

My automation is exactly the same as @basnijholt, except I notify another device of course. This is what I see in the developer tool:
```
light: {{ "light.desk" }}

{{ state_attr("switch.adaptive_lighting_bedroom", "manual_control") }}

{{ light in state_attr("switch.adaptive_lighting_bedroom", "manual_control") }}

{{ "light.desk" in state_attr("switch.adaptive_lighting_bedroom", "manual_control") }}
```

And this is the output:

```
light: light.desk

['light.desk']

False

True
```

What is happening here, I don't really understand. My reasoning is correct right? But in any case, the automation is always failing on this condition in the ```action``` segment of the automation.

**Comment by Chreece** [comment]
The output is correct with what you have given.
Here you can find the parameters for the service adaptive_lighting.set_manual_control you have the following attributes to declare:
![Screenshot_20210819-124022_Chrome](https://user-images.githubusercontent.com/68458228/130055636-ca8a211b-c048-465e-a161-0a55d2f8cf3d.jpg)
This means you should have something like that:
``` 
- service: adaptive_lighting.set_manual_control
  data:
    entity_id: switch.adaptive_lighting_bedroom
    lights: light.desk
    manual_control: true (*** or false ***)
```

**Comment by JDFS404** [comment]
But why is it not working with the variable "light" set? Because that means I need to make an automation for every switch and every light that I have...

**Comment by Chreece** [comment]
Where did you declare this variable?

**Comment by Chreece** [comment]
You could make a script and there you could that:

``` 
- service: adaptive_lighting.set_manual_control
  data:
    entity_id: '{{ switch }}'
    lights: '{{ light }}'
    manual_control: '{{ manual }}'
```

Now you need to pass the values to this script with:
```
- service: script.turn_on
  data:
    variables:
      switch: < switch name >
      light: < light name >
      manual: < true or false >
  entity_id: script.< the name from your script >
```
Or did I missunderstood what you want to achieve?
```

**Comment by JDFS404** [comment]
Thanks @Chreece for your help so far, this is my automation as it is:

```
alias: 'Adaptive Lighting: Reset Manual Control'
id: reset_manual_control
mode: parallel
max: 200
trigger:
  - platform: event
    event_type: adaptive_lighting.manual_control
variables:
  light: '{{ trigger.event.data.entity_id }}'
  switch: '{{ trigger.event.data.switch }}'
condition: []
action:
  - delay:
      seconds: 10
  - condition: template
    value_template: '{{ light in state_attr(''switch'', ''manual_control'') }}'
  - alias: Set manual_control
    service: adaptive_lighting.set_manual_control
    data:
      entity_id: '{{ switch }}'
      lights: '{{ light }}'
      manual_control: false
  - alias: Notify devices
    service: notify.justin
    data:
      title: 'Adaptive Ligthing: manual_control reset'
      message: '{{ light }} is reset to automatically controlled.'
```

It stops here for every light that is manually controlled and thus does not reset the manual control to ```false```:
![image](https://user-images.githubusercontent.com/26678110/130065504-0c69abea-7242-4682-ace1-bb3b85af8d8e.png)

**Comment by Chreece** [comment]
That's right... Your automation doesn't know what the variable light, switch and manual_control is...

Please explain me in plain language what exactly you want to achieve and then we can translate that to an automation or script

**Comment by Chreece** [comment]
value_template: '{{ light in state_attr(''switch'', ''manual_control'') }}'

That should be:

```
value_template: '{{ light in state_attr(switch, "manual_control") }}'
```

**Comment by JDFS404** [comment]
I want to achieve exactly what @basnijholt has written on the readme, use 1 automation to reset manual control (https://github.com/basnijholt/adaptive-lighting#automation-examples). In his own config he even has the same automation so either it's outdated or I am doing something wrong. Or maybe I did not read correct, but I see that HA picks up every light that is manually controlled (see below):
![image](https://user-images.githubusercontent.com/26678110/130066532-909d9c3e-3013-40e9-9eee-e9604157c3f1.png)

To me it seems these variables are passed through right and can be used by the automation?

**Comment by Chreece** [comment]
Yes sorry, I didn't see the declaration of the variables in your automation. Try the fix in my last post

**Comment by JDFS404** [comment]
This was it @Chreece you're the man! It seems that you need to be very nitpicky working with template coding... It worked immediately. Let me make a suggestion to @basnijholt to change his Readme.

**Comment by JDFS404** [comment]
Leaving this for posterity, my automation which works now:
```
---
# Automation to reset Manual Control for Adaptive Lighting after one hour
# 
alias: "Adaptive Lighting: Reset Manual Control"

id: reset_manual_control

mode: parallel
  
max: 200
  
trigger:
  - platform: event
    event_type: adaptive_lighting.manual_control

variables:
  light: "{{ trigger.event.data.entity_id }}"
  switch: "{{ trigger.event.data.switch }}"

condition:
  []

action:
  - delay:
      hours: 1

  - condition: template
    value_template: "{{ light in state_attr(switch, 'manual_control') }}"

  - alias: "Set manual_control"
    service: adaptive_lighting.set_manual_control
    data:
      entity_id: "{{ switch }}"
      lights: "{{ light }}"
      manual_control: false

  - alias: "Notify devices"
    service: notify.justin
    data:
      title: "Adaptive Ligthing: manual_control reset"
      message: "{{ light }} is reset to automatically controlled."
```
