### ISSUE TITLE
Relative dimming

### ISSUE THREAD

**Issue by aeklo** [basnijholt/adaptive-lighting#184]
Would love to see relative dimming in %.

My example: I have 10 Hue spots all set up with a bit different brightness in a scene (more on the walls, less on the couch etc.). When adaptive lighting takes control, they are all set to the same brightness, breaking the tuned, independant levels. One single check-box with "Relative dimming" would solve this, I believe.

Thanks for a really great plug-in!

**Comment by itssimon** [comment]
Great suggestions here that I would find very useful. If implemented, the configuration could look like this:

```yaml
adaptive_lighting:
  - name: Default
    lights:
      light.downlights: {}
      light.desk_lamp:
        max_brightness: 60
        min_color_temp: 3000
    min_brightness: 80
    min_color_temp: 2700  # applies to all lights that don't have this set individually
    max_color_temp: 5500
```

Of course supplying just a list of `lights` should continue to be supported as well.
