### ISSUE TITLE
add min/max brightness and min/max sleep mode brightness to apply service call

### ISSUE THREAD

**Issue by oddboy** [basnijholt/adaptive-lighting#185]
Hi all,

Thank you to everyone that made this integration.  It's really awesome!

I was wondering if there's an appetite to add the ability to set min/max brightness and min/max sleep mode brightness to the adaptive_lighting.apply service call.

In my case, I'd like the ability to set these options programatically (I use appdaemon, but i imagine the same could be used in a traditional automation too).  This would allow me to adjust the adaptive lighting config in response to other events. 

For example, I'd like to set min brightness to a higher value on weekend nights, but then return it to "normal" (lower value) on week day nights.

So far, that's the only item I've come across that I'd change for this integration... 😄 

cheers,

J

**Comment by Nick398** [comment]
I have a similar request. I'd like to decrease the brightest when there's more natural light coming to the room as captured by a Lux sensor. This would cause for sunny/cloudy days to adjust the brightness accordingly.

**Comment by jarrah31** [comment]
I would like this too please.

I have an adaptive light switch that usually has a max and min brightness of 2%:
```
adaptive_lighting:
  - name: famrm_coving
    lights: 
      - light.family_room
    take_over_control: true
    max_brightness: 2
    min_brightness: 2
```
This is activated when I press a switch to turn the lights on:
```
  - service: light.turn_on
    entity_id: light.family_room
```
However, there are times when I would like to have full brightness _and_ continue to adapt the colour at the same time. I would therefore like to use adaptive_lighting.apply to override the settings from the switch with something like the following:
```
      - service: adaptive_lighting.apply
        entity_id: switch.adaptive_lighting_famrm_coving
        data:
          lights: light.family_room
          transition: 1
          turn_on_lights: true
          adapt_brightness: true
          adapt_color: true
          min_brightness: 100
```
At the moment I use the take_over_control feature along with the following service call to make the lights go full bright, it's just that they then don't adapt their colour.
```
      - service: light.turn_on
        entity_id: 
          - light.family_room
        data:
          brightness: 255
```
