### ISSUE TITLE
Referenced entities from deleted integrations are not cleaned up

### ISSUE THREAD

**Issue by mvdwetering** [basnijholt/adaptive-lighting#220]
#### Version information:

1.0.14

#### Description:

I removed the integration I was using for my lights and now use another one. I wanted to change the assigned lights that the adaptive-lighting integration uses. However the "lights" selection still shows the entitity of the integration I removed (using the UI of HA), but since it is not in the list I can not uncheck it and trying to save results in an error message "User input malformed".

Only way around it seems to be to delete the configuration and add a new one

**Comment by K-4U** [comment]
Think i'm running against this same issue

**Comment by alexvdleek** [comment]
Exact same problem here.

**Comment by EmnaX** [comment]
Me too! I changed the name from light.wled to light.basement_stairs_wled and now I can't delete the light.wled entity!

Running on Home Assistant 2021.12.1 with Adaptive Lighting 1.0.14.

![Screen Shot 2021-12-13 at 2 00 53 PM](https://user-images.githubusercontent.com/13283601/145872328-66e8c8c3-4457-4be6-8b78-d9b8925c2ffb.png)

**Comment by broyuken** [comment]
+1

**Comment by peterbaker** [comment]
+1

**Comment by guinnberg** [comment]
I'm having the same issue, is there any way to modify this configuration from YAML manually?

**Comment by EmnaX** [comment]
hmm, I don't think you can modify the integration from yaml... BUT you can just set it up in yaml and use it going forward. Here is what I have in there now:
```
- name: "Basement Stairs"
  lights:
    - light.basement_stairs_wled
  prefer_rgb_color: false
  transition: 45
  initial_transition: 1
  interval: 90
  min_brightness: 30
  max_brightness: 100
  min_color_temp: 2000
  max_color_temp: 5500
  sleep_brightness: 10
  sleep_color_temp: 1000
  sunrise_time: "07:00:00"  # override the sunrise time
  sunrise_offset: 0
  sunset_time: "20:00:00"
  sunset_offset: 0  # 1800 (in seconds) or '00:15:00'
  take_over_control: true
  detect_non_ha_changes: false
  only_once: false
```
