### ISSUE TITLE
Does not store brightness values

### ISSUE THREAD

**Issue by rbalaev** [basnijholt/adaptive-lighting#223]
#### Version information:
1.0.14

#### Description:
Does not store brightness values. After changing the slider and saving, the value remains at the same level.

<img width="324" alt="image" src="https://user-images.githubusercontent.com/90223039/143212220-3d0857a3-f8bb-4bba-9c2b-803e0b04fb4e.png">

**Comment by acoutts** [comment]
I found using yaml to configure it resolves this issue.

**Comment by hanfelt** [comment]
> I found using yaml to configure it resolves this issue.

Would you mind sharing how to do this?

**Comment by andrejkolesa** [comment]
I can confirm this issue.
And to add: Not only it does not save, it save different value sometimes.
If i set brightness to 90% it will save to 20%, other time to 30% ...

**Comment by Radixtrator** [comment]
I am running into the same issue.
I have also not found the yaml..

**Comment by anroots** [comment]
Experiencing something similar

> I found using yaml to configure it resolves this issue.

Ditching GUI and setting values in code helped. For my use case (similar to #212) I only want temperature control, so I set both min and max brightness to 100%. Works.

> Would you mind sharing how to do this?
> I have also not found the yaml..

You need to install the "File editor" addon, then use this to open `configuration.yaml`.  Add new block of something like:

```yaml
adaptive_lighting:
  name: default_adaptive
  lights:
    - light.bedroom_light
  max_brightness: 100
  min_brightness: 100
  min_color_temp: 2500
  max_color_temp: 5500
```

Refer to the readme of this project, and keep in mind this will disable the web UI for AL.
https://www.home-assistant.io/docs/configuration/
