### ISSUE TITLE
Lights turn on by themself

### ISSUE THREAD

**Issue by marithpl** [basnijholt/adaptive-lighting#246]
#### Description:
I've noticed a problem with 3 of my bulbs (Hue via Hue Bridge, Ikea via Deconz) that lights sometimes turn on by themselves.
I was looking for a reason for about 1 month and yesterday I turned off Adaptive Lightning Integration for this lights.
After about 24 hour I didn't noticed this problem. So it should be related with this integration.

Usually logs of my bulbs looks like this:
<img width="368" alt="Zrzut ekranu 2021-12-13 o 20 44 10" src="https://user-images.githubusercontent.com/25366097/149124529-2edec089-190d-4275-85e2-68171551a56f.png">
In translations automation turn on a bulb,
after that turning off because of state_changed
and after that turn on light by service light.turn_on

To be sure I still using the same automation before and after disabling integration.

Is anyone have the same problem or also have a solution for that?

Im really missing the sleep mode when bulbs are on 1% brightness.

And here is my automation:
```
alias: 🏃 [Piętro] Turn on light on motion (v 2.0 with bug)
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.presence_79
    to: 'on'
    from: 'off'
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.lightlevel_80
            below: '100'
        sequence:
          - service: light.turn_on
            data: {}
            entity_id: light.color_temperature_light_18
          - wait_for_trigger:
              - platform: state
                entity_id: binary_sensor.presence_79
                from: 'on'
                to: 'off'
                for:
                  hours: 0
                  minutes: 0
                  seconds: 10
          - service: light.turn_off
            data: {}
            entity_id: light.color_temperature_light_18
    default:
      - service: light.turn_off
        target:
          entity_id: light.color_temperature_light_18
mode: restart
```

**Comment by maartenlandman89** [comment]
I've got the same problem. When i turn off all light, some of them are turning on by themself after a few seconds. I have Ikea lights with Zigbee2MQTT and Conbee 2. 
In the logs i can't find a reason for it..

**Comment by markunca** [comment]
The same for me started from yesterday with version 1.0.15. Two of my 20+ bulbs doing it.

**Comment by marithpl** [comment]
Good to see that I'm not alone.
Guys what bulbs usually turn on by themselves? In my case it's Ikea GU10, Ikea Floalt, Gledopto RGBCCT Controller

**Comment by markunca** [comment]
Ikea Floalt, different types of Ikea Bulbs (E27 LEDs) with Ikea Gateway and remotes

**Comment by marithpl** [comment]
In my case I have bulbs connected to Hue Bridge or Deconz/Conbee II

**Comment by BadCo-NZ** [comment]
I am also having issues with lights turning back on.

I am using Shelly duo's and Shelly Dimmers.

**Comment by confucius78** [comment]
Same here. All ikea lights with ikea bridge

**Comment by Shin-nn** [comment]
I have the same issue, do not have much time do dig inside, it looks like adaptive lightning has old information about light status. Just quickly checked the code - in case of philips hue, it is possible to send just a change color command without turning on, but Home assistant has no support for that... would it be solution?

**Comment by confucius78** [comment]
Over the weekend I tested a bit further and found the issue even occurs with the integration switched off!

I created an automation which switches off the integration and then the lights. Even after running that, several lights are switching back on.

**Comment by BadCo-NZ** [comment]
> Over the weekend I tested a bit further and found the issue even occurs with the integration switched off!
> 
> I created an automation which switches off the integration and then the lights. Even after running that, several lights are switching back on.

Did you still have the automation ```Adaptive lighting: reset manual_control after 1 hours``` enabled?

**Comment by confucius78** [comment]
Sorry, not sure what you mean by that. There are no other automations running that control the lights or adaptive lighting, unless there is something running in the background through the integration.

To clarify my earlier comment: after the integration and (after that) the lights are switched off, the lights come back on for a minute or so. As if there are a couple of adjustments still in the queue which are then executed. I don't have time to dig through the code, but it seems there is no on/off check prior to issuing a brightness/color update. I think someone mentioned this before, but at least Ikea lights switch on when brightness is adjusted, even without sending an explicit on command.

After switching off a second time the lights do stay off when the integration is disabled.

This is an issue I have noticed before, so it is not related to that, but FYI currently running HA latest beta 2022-02.

**Comment by BadCo-NZ** [comment]
> Sorry, not sure what you mean by that. There are no other automations running that control the lights or adaptive lighting, unless there is something running in the background through the integration.
> 
> To clarify my earlier comment: after the integration and (after that) the lights are switched off, the lights come back on for a minute or so. As if there are a couple of adjustments still in the queue which are then executed. I don't have time to dig through the code, but it seems there is no on/off check prior to issuing a brightness/color update. I think someone mentioned this before, but at least Ikea lights switch on when brightness is adjusted, even without sending an explicit on command.
> 
> After switching off a second time the lights do stay off when the integration is disabled.
> 
> This is an issue I have noticed before, so it is not related to that, but FYI currently running HA latest beta 2022-02.

[See here](https://github.com/basnijholt/adaptive-lighting#automation-examples)

**Comment by confucius78** [comment]
If you refer to the automation example in the readme: no that is not running

**Comment by jabbink** [comment]
Briefly tried to debug this and it seems like https://github.com/basnijholt/adaptive-lighting/blob/master/custom_components/adaptive_lighting/switch.py#L1486 checks for the transition used to `turn_off`

change your calls to
```yaml
- service: light.turn_off
  data:
    transition: 0
  target:
    entity_id: [entity]
```
and see if it's fixed for you. Tested it a couple of times for me, and so far the lights stay off
