### ISSUE TITLE
WLED light is not turning off properly if AL is enabled

### ISSUE THREAD

**Issue by d-dsn** [basnijholt/adaptive-lighting#251]
#### Version information:
Version 1.0.15

#### Description:
I'm having WLED light with SK6812 (WWA color configuration). If the Adaptive Lighting component is on, and has been on for a few minutes(?), it sometimes becomes hard to switch the light off from HA by (light.turn_off) because the WLED light goes into somekind of a flicked-state where it gradually fades to off by flickering. When doing the off-flickering, if I immediately command "turn_on" and "turn_off" again, it turns off.

 This is my AL-config and I'm adapting to both colour and brightness:

```
- name: "Akustiikkataulu"
    lights:
    - light.akustiikkataulu
    prefer_rgb_color: false
    transition: 45
    initial_transition: 1
    interval: 90
    min_brightness: 3
    max_brightness: 50
    min_color_temp: 1500
    max_color_temp: 5000
    sleep_brightness: 1
    sleep_color_temp: 2000
#    sunrise_time: "09:00:00"  # override the sunrise time
    sunrise_offset: -1600
#    sunset_time: "13:00:00"
#    sunset_offset: '01:00:00'
    take_over_control: true
    detect_non_ha_changes: true
    only_once: false
```
