### ISSUE TITLE
White Value (White Light Brightness) not being set

### ISSUE THREAD

**Issue by forstermatth** [basnijholt/adaptive-lighting#26]
_This is the last thing blocking me from fully migrating from CL. This was also a rubber duck exercise, but I figured I would post the issue anyways._

I have some ESPHome flashed Tuya bulbs, which have four channels; **(RBG, Brightness) and (Color Temp, White Value)**. Brightness affects the brightness of the RBG diode, and White Value controls the brightness of the White diode. Each pair can be set individually and does not affect the other.

I'm looking through the switch, and I see you have White Value in the enums, but it's not being used. I've tested the bulbs with AL and it sets the colour correctly, but the brightness of the white diode never changes.

Here is the state for the bulbs in question;

```yaml
min_mireds: 200
max_mireds: 500
brightness: 254
color_temp: 400
hs_color:
  - 28
  - 17.647
rgb_color:
  - 255
  - 231
  - 210
xy_color:
  - 0.367
  - 0.349
white_value: 254
friendly_name: Bulb - Living Room
icon: 'mdi:lamp'
supported_features: 187
```

I will be looking at adding this and testing with my own bulbs locally, but I just wanted to confirm that I was looking at this in the right way;

1. Adding White Value to the imports from HA Core; https://github.com/basnijholt/adaptive-lighting/blob/master/custom_components/adaptive_lighting/switch.py#L34-L37
2. Adding White Value to the Supported options; https://github.com/basnijholt/adaptive-lighting/blob/master/custom_components/adaptive_lighting/switch.py#L123-L128
3. Add a White Value to the `service_data` being set, using the same brightness value; https://github.com/basnijholt/adaptive-lighting/blob/master/custom_components/adaptive_lighting/switch.py#L683-L685

For reference, here are the declared bitmap values for the light entity; https://github.com/home-assistant/core/blob/master/homeassistant/components/light/__init__.py#L35-L41
