### ISSUE TITLE
Synchronize brightness with sun position

### ISSUE THREAD

**Issue by bnason** [basnijholt/adaptive-lighting#264]
I'm not sure if this has been asked before as I couldn't find anything in a search and this is how I assumed adaptive lighting actually worked before really reading the readme.

Effectively, I would like my lights to turn on to min brightness at sunrise and rise to max brightness at solar noon. Optionally, keeping the lights at min brightness all night or turning them off.

I'm not sure if this "mode" would be better added directly in or if a fork would be preferred.

**Comment by bnason** [comment]
So I figured out a poor mans way of doing this using some custom helpers, sensors and automations. Note, I have a night time sensor that's basically inverted so I can control my patio lights. I'm also very new to home assistant so excuse me if there is a better way to even do this workaround.

The major problem with this implementation is the lack of override controls as well as the lights not consistently being updated as the automation doesn't seem to run all the time for me.

# Custom helpers
input_number.lights_max_brightness
input_number.lights_min_brightness

# Custom sensors
```
- platform: template
  sensors:
    solar_lighting_brightness:
      unit_of_measurement: "%"
      value_template: >
        {{ (states('input_number.lights_max_brightness')|int - states('input_number.lights_min_brightness')|int) * (max(0, min(100, states('sensor.adaptive_lighting_sun_position')|float)) / 100) + states('input_number.lights_min_brightness')|int }}

- platform: template
  sensors:
    solar_lighting_brightness_night:
      unit_of_measurement: "%"
      value_template: >
        {{ (states('input_number.lights_max_brightness')|int - states('input_number.lights_min_brightness')|int) * (max(0, min(0, (states('sensor.adaptive_lighting_sun_position')|float) * -1)) / 100) + states('input_number.lights_min_brightness')|int }}
```

# Day Time Automation
```
alias: Solar Light Brightness
description: ''
trigger:
  - platform: state
    entity_id: sensor.solar_lighting_brightness
condition: []
action:
  - service: light.turn_on
    data:
      brightness_pct: '{{ states(''sensor.solar_lighting_brightness'')|float }}'
    target:
      device_id:
        - xxx
        - yyy
mode: single
```

# Night Time Automation
```
alias: Solar Light Brightness Night
description: ''
trigger:
  - platform: state
    entity_id: sensor.solar_lighting_brightness_night
condition:
  - condition: sun
    before: sunrise
    after: sunrise
    before_offset: '3599'
    after_offset: '2599'
action:
  - service: light.turn_on
    data:
      brightness_pct: '{{ states(''sensor.solar_lighting_brightness_night'')|float }}'
    target:
      device_id:
        - zzz
mode: single
```
