### ISSUE TITLE
Possible for AL to update the color of a Hue Scene?

### ISSUE THREAD

**Issue by GollyJer** [basnijholt/adaptive-lighting#271]
Hi, I have a full Philips Hue setup with Lutron Aurora switches and Hue motion detector "switches".  Home Assistant doesn't work great for controlling the lights with these switches.

It is also jarring to mix AL with Hue controlled switches because they come on at whatever their last setting was and then AL eventually updates the light. 

I've been trying to think of workarounds that would allow the use of Hue Hub as the hardware controller but immediately turn on the lights to the current AL level.

The only idea I currently have leads to this question...

**Is possible to have AL update the settings of a Hue scene at the same rate it updates the lights?** This way all the switches and motion detectors could set their "when turned on" to the scene being updated with AL.

**Comment by gderber** [comment]
While I'd love it if the integration could do it natively, I am not sure how.

It is currently possible to do this from Home Assistant.  I thought about simply linking a How-to I quickly wrote in my configuration file, but decided that link could change so I am re-posting here.

You can find my configuration at: https://github.com/hearthminion/homeassistant_config

This is only in the development branch, under packages/lighting/

Eventually the development branch will merge into the main branch, and the development branch will be eliminated.

# How to Update HomeAssistant Scene on Hue Bridge.

Note I configured my lighting setup and automations entirely in yaml.

## Variables
#### hue_bridge: IP address or Hostname for Hue bridge, eg '192.168.92.5' or 'hue.example.com'
#### hue_application_key
The hue application key used for authentication to the bridge.

You can find this in your home-assistant config inside the storage directory. eg: /srv/homeassistant/config/.storage/
The file to read through is core.config_entries.  You are looking for a section that looks like:

```
{
  "entry_id": "0123456789abcd",
  "version": 1,
  "domain": "hue",
  "title": "Hue Bridge",
  "data": {
    "host": "{{ hue_bridge }}",
    "api_key": "{{ hue_application_key }}",
    "api_version": 2
  },
...
}
```

The line with *api_key* is your hue_application_key.

In this example the key is stored as a secret in secrets.yaml as 'hue_username'

## Create HomeAssistant Scene on Hue Bridge.

Use the Hue App.  Create a scene to be managed by Home Assistant.  I personally named mine 'HomeAssistant'.

## Identify Scenes and Light bulbs

curl --insecure -H 'hue-application-key: {{ hue_application_key }} ' -X GET 'https://{{ hue_bridge }}/clip/v2/resource/scene' | jq > scenes.json

Will save your scenes to scenes.json

### Identify Lights
curl --insecure -H 'hue-application-key: {{ hue_application_key }} ' -X GET 'https://{{ hue_bridge }}/clip/v2/resource/light' | jq > lights.json

Will save your lights to lights.json

Note: you do not really need the lights.json file.  It is useful for verifying the light you have
selected in your scene is the correct one.

## Edit your Home Assistant Configuration

### Create rest_command integration
```
rest_command:
  light_update_den_scene:
    url: "https://{{ hue_bridge }}/clip/v2/resource/scene/{{ scene_id }}"
    method: put
    headers:
      hue-application-key: "{{ username }}"
    payload: '{
          "id":"{{ scene_id }}",
          "actions":[
          {
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid": "02186fdb-4ea0-440a-80ad-c0d9adc69527","rtype":"light"}
          },
          {
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid": "f8aca0e4-1a6c-4cac-9d08-ecf09cbdf5d6","rtype":"light"}
          },
          {
          "action":{ {{ color }},{{ brightness }},{{ on_state }} },
          "target":{"rid": "4294ad46-44e2-4df9-974e-d28c65fb308a","rtype":"light"}
   }
```

Each light bulb in the scene will require an action.  The rid you will get from scenes.json, by looking
for the light bulb associated with the scene to be updated.

### Create script to call the rest commands.

I did this because I have one scene per light fixture, and one scene per room to be edited.  This
means there are over 30+ scenes in my configuration to be modified every time the script is run.  To
prevent the hue hub from being overwhelmed with requests all at once, I use a script that runs the
rest command sequentially with 1 second between each call.

In addition, by using a script, I can send variables to the rest command to make the rest command
more versatile, for updating in other scenarios.

```
script:
  light_update_scene_homeassistant:
    alias: "[Light] Update Home Assistant Scenes"
    mode: single
    sequence:

      - service: rest_command.light_update_den_scene
        data:
          scene_id: "0fad44f3-9093-4f05-86e9-4aeb8467b4fc"
          username: !secret hue_username
          color: '"color_temperature":{ "mirek":{{ states("sensor.global_dummy_light_color_temperature") | int(367) }} }'
          brightness: '"dimming":{ "brightness": {{ states("sensor.global_dummy_light_brightness") | int(100) }} }'
          on_state: '"on":{"on":true}'

      - alias: "Wait 1s"
        delay: 1

      - service: rest_command.light_update_den_scene
        data:
          scene_id: "a77ec553-6f7f-4187-a42b-fac3e50c3e33"
          username: !secret hue_username
          color: '"color_temperature":{ "mirek":{{ states("sensor.global_dummy_light_color_temperature") | int(367) }} }'
          brightness: '"dimming":{ "brightness": {{ states("sensor.global_dummy_light_brightness") | int(100) }} }'
          on_state: '"on":{"on":true}'

      - alias: "Wait 1s"
        delay: 1

...
```

You'll get the scene_id from scenes.json.  Look through the file to identify the scene_id for the
scene you wish Home Assistant to update.

### Create Global Adaptive Lighting Entity

This entity is *always* on.  I created this because if the entities are switched off, their
attributes are not available for scripting.  I wanted an entity that was guaranteed to always be on.

```
adaptive_lighting:
  - name: "Global: Dummy Light"
    initial_transition: 1
    min_color_temp: 2000
    max_color_temp: 6500
```

### Create template sensors

This may be redundant, You can theoretically use the state attributes directly in the above script.

```
template:
  - sensor:
      - unique_id: "0639ee4e-55ff-41af-a903-ff6db2660b1e"
        name: "Global Dummy Light Brightness"
        state: >-
          {% if state_attr("switch.adaptive_lighting_global_dummy_light", "brightness_pct") == None or
          is_state_attr("switch.adaptive_lighting_global_dummy_light", "brightness_pct", "unknown") or
          is_state_attr("switch.adaptive_lighting_global_dummy_light", "brightness_pct", "off") %}
            100
          {% else %}
            {{ state_attr("switch.adaptive_lighting_global_dummy_light", "brightness_pct") | int(100) }}
          {% endif %}
        unit_of_measurement: "%"

      - unique_id: "0e8a672a-9db0-40bd-9727-d0b206802b80"
        name: "Global Dummy Light Color Temperature"
        state: >-
          {% if state_attr("switch.adaptive_lighting_global_dummy_light", "color_temp_mired") == None or
          is_state_attr("switch.adaptive_lighting_global_dummy_light", "color_temp_mired", "unknown") or
          is_state_attr("switch.adaptive_lighting_global_dummy_light", "color_temp_mired", "off") %}
              367
          {% else %}
            {{ state_attr("switch.adaptive_lighting_global_dummy_light", "color_temp_mired") | int(367) }}
          {% endif %}
        state_class: measurement
```

In this case I manually set the unique_id using ```uuidgen -r```, this is not required.  Some of
this code may be redundant.


Hope this helps.  There is probably a more efficient way of doing this.  This is still a heavy work in progress for me.
