### ISSUE TITLE
set_manual_control: Make `lights` attribute optional 

### ISSUE THREAD

**Issue by brianhanifin** [basnijholt/adaptive-lighting#28]
Per [your request](https://community.home-assistant.io/t/circadian-lighting-possible-fix-to-keep-light-groups-off/221188/14) I am officially making a feature request.

Proposed `adaptive_lighting.set_manual_control` changes:
1. Make `lights` optional.
2. Apply the change to all lights in represented by the `entity_id` when `lights` is not set.

I think it is safe to assume if a user *chooses* to omit the `lights` attribute that they expect the effect to be applied to all lights in that group.

Here is an mock-up of a situation where I am currently being forced to attempt to use an (as yet untested) template to expand a list of entities in a group, to set manual_control to false.

```
# Set the example value of the area variable.
- variables:
    area: 'play_room'

# Restore Adaptive Lighting for all lights in this area.
- service: adaptive_lighting.set_manual_control
  data:
    entity_id: 'switch.adaptive_lighting_{{ area }}'
    lights: '{{ expand("group." ~ area ~ "lights") | map(attribute="entity_id") | list }}'
    manual_control: false
```
