### ISSUE TITLE
Initial Adjustment Delay

### ISSUE THREAD

**Issue by sphbecker** [basnijholt/adaptive-lighting#307]
I assume HA raises an event when a device goes from offline to online, could Adaptive Lighting listen for that event and trigger an initial transition?

Back story: I switched to Adaptive Lighting from Circadian Lighting. Overall, I think Adaptive Lighting is a more mature project, but one thing lacking is that Adaptive Lighting is MUCH slower on the initial transition when smart bulbs are turned on with a dumb switch. I use primarily Wiz bulbs. Circadian was able to set the correct color as soon as the bulb registered with HA, typically within 1-2 seconds. Adaptive Lighting seems to miss this type of event and the bulb remains at its power-on default until the next interval.

**Comment by abigdeel** [comment]
Made the exact same switch here. Wiz lights to HA based circadian rhythm.

It is very possible to do this, even with a blueprint or automation. The device returns a state_changed event from unavailable to on when this happens.

It really should be added into this integration as a feature, it's not as simple to implement for the average user if you have lots of lights affected.

**Comment by abigdeel** [comment]
For the time being, I'm using this terribly inefficient automation to do the trick:

```
alias: Adaptive Lighting - Unavailable to ON Apply
description: ""
trigger:
  - platform: state
    entity_id:
      - light.cree_bulb_lr_1
      - light.cree_bulb_lr_2
    from: unavailable
    to: "on"
    id: lr
  - platform: state
    entity_id:
      - light.bulbrite_kc_1
............
    id: kitchen
condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: lr
        sequence:
          - service: adaptive_lighting.apply
            data:
              entity_id: switch.adaptive_lighting_living_room
  - choose:
.........
```

**Comment by cameronurnes** [comment]
For automations what I did was add a sensor which checks the adaptive lighting brightness level attribute, so auto-on automations can set to the correct level.  This doesn't particularly help with other methods of turning the lights on though.

**Comment by robcresswell** [comment]
@cameronurnes Can you share the yaml for that?

**Comment by th3w1zard1** [comment]
Don't most light bulbs come with `power_on_state: on | off | last_known` that you can configure?

If your lights are becoming unavailable due to a connection issue in your home, I don't see how programming `adaptive-lighting` to work around those pre-existing connection issues would help, if anything it'd make the problem more complex and harder to diagnose later on.

Other helpful relevant config options you might have missed:
          "interval": "interval: Time between switch updates. (seconds)",
          "initial_transition": "initial_transition: When lights turn 'off' to 'on'. (seconds)",
          "sleep_transition": "sleep_transition: When 'sleep_state' changes. (seconds)",
          "transition": "Transition time when applying a change to the lights (seconds)",

**Comment by sphbecker** [comment]
> Don't most light bulbs come with `power_on_state: on | off | last_known` that you can configure?
> 
> If your lights are becoming unavailable due to a connection issue in your home, I don't see how programming `adaptive-lighting` to work around those pre-existing connection issues would help, if anything it'd make the problem more complex and harder to diagnose later on.
> 
> Other helpful relevant config options you might have missed:
> 
> `interval`: "interval: Time between switch updates. (seconds)", `initial_transition`: "initial_transition: When lights turn 'off' to 'on'. (seconds)", `sleep_transition`: "sleep_transition: When 'sleep_state' changes. (seconds)", `transition`: "Transition time when applying a change to the lights (seconds)", `adapt_delay`: "Wait time in seconds between light turn on, and Adaptive Lights applying changes to the light state. May avoid flickering."

Thank you for the reply. I realize did a poor job explaining the use case. When I referred to the "device going offline" I meant a smart bulb being powered off by a physical switch, not a connection issue. The basic issue is that when power is restored to the bulb, it is interpreted by adaptive-lighting as a manual change (at least for my WiZ bulbs), which I argue is not the desired effect.

I have a perfectly fine work-around, created an automation that listens for the bulb to leave the unavailable state, pause about 300ms and then tell adaptive-listing to turn off manual control for that bulb. I can understand if there are no plans to address this, but I wanted to make sure I correctly explained my usage.

PS: yes, I am one of those old school people who prefers having physical switches in some settings. I have started installing Shelly's behind many of my switches so that I can use them for control without cutting power to the bulb, but I don't yet have a Shelly behind every switch.

**Comment by th3w1zard1** [comment]
This is very odd as when my devices become unavailable they fire OFF state changes to hass. Is there no way you can simply do that?

Adaptive lighting will adapt any off->on state changes, and will set manually controlled when it finds on->on state changes (e.g brightness diff) not caused by the integration.

**Comment by th3w1zard1** [comment]
Well that's what home assistant is for, you'd need to fire a state change event, I'm not exactly sure how you could do this.

**Comment by robcresswell** [comment]
@th3w1zard1 It'd be fairly trivial I think, but mapping your unavailable devices to off would probably break other behaviours

**Comment by basnijholt** [comment]
Could anyone share debugging logs? Then I can understand what's going on.

**Comment by basnijholt** [comment]
I believe this is the same as https://github.com/basnijholt/adaptive-lighting/issues/96

**Comment by marvinpowell** [comment]
I have the same issue:

Some Ikea Tradfri Lights that are controlled by physical switches. I use zigbee2mqtt. I currently have manual control turned off completely.

When I turn on the lights, they almost immediately switch from unavailable to on in HA. But AL will apply it's settings only after the next interval, which in my case can be up to 5 minutes.

Is this by design? I guess I could work around it if i make an automation for every light to apply AL settings when state changes from unavailable to on. But that seems like a hassle to me.

**Comment by marvinpowell** [comment]
For everyone using physical switches and using zigbee2mqtt, this is my current workaround:

I did not use the state change from Unavailable to On as Trigger, because that didn't work when the lights were only off for a couple of seconds or minutes - zigbee2mqtt only puts the devices in the unavailable state after 10 minutes.

Instead I created an automation that uses the MQTT Trigger and tries to apply the AL settings on every "DEVICE ANNOUNCE", so every time the light powers up.

I don't need an automation for every light. This automation works for all light.
There is potential to improve it, for example one could add a condition to check if the entity exists and if adaptive lighting is enabled before running the action, but it works for me.

```
alias: Adaptive Lighting - Apply on Device Announce
description: ""
trigger:
  - platform: mqtt
    topic: zigbee2mqtt/bridge/event
condition:
  - condition: template
    value_template: "{{ trigger.payload_json.type == \"device_announce\" }}"
action:
  - service: adaptive_lighting.apply
    data:
      lights:
        - light.{{ trigger.payload_json.data.ieee_address }}
      transition: "1"
mode: single
```
