### ISSUE TITLE
Adapting lights when they turn on after being unavailable

### ISSUE THREAD

**Issue by nicogramm** [basnijholt/adaptive-lighting#33]
Hi,

I have a smart bulb I have to physically plug into and out of an outlet at the beginning of the day and at the end of the day.
The way adaptive lighting works rn is that if a lamp gets turned on (off -> on) it gets automatically adapted.
What I'm looking for is lamps also getting adapted if they get physically turned on (the state going unavailable -> on).

It's awesome if that would be possible!
Many thanks for the awesome work you and the other contributers put into adaptive lighting already, I really enjoy using it!

**Comment by basnijholt** [comment]
I purposely chose to not support this option. This is because when a light is manually controlled and briefly becomes unavailable and then back, it will loose its 'manually controlled' status.

You can probably set up an automation like:
```yaml
- alias: "Turn on Adaptive Lighting"
  trigger:
    platform: state
    entity_id: light.somelight
    from: "unavailable"
    to: "on"
  condition:
    - service: switch.turn_off
      entity_id: switch.adaptive_lighting_default
    - service: switch.turn_on
      entity_id: switch.adaptive_lighting_default
```
to get this behavior.

**Comment by basnijholt** [comment]
Closing, let me know if my suggestion didn't work.

**Comment by pierosavi** [comment]
Same situation here, this worked for me

```
alias: Reset Adaptive Lighting
  trigger:
  - platform: state
    entity_id: light.somelight
    from: unavailable
    to: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.adaptive_lighting_general
  - delay: '1'
  - service: switch.turn_on
    entity_id: switch.adaptive_lighting_general
```

I had a weird issues without the 1 second delay where the lights wouldn't turn 100% on even if they should have.
Executing the action manually worked fine without the delay.
This is probably due the fact that they are a light group.
