### ISSUE TITLE
Controlling one bulb in a ZHA light group affects all the bulbs in the group

### ISSUE THREAD

**Issue by daFreeMan** [basnijholt/adaptive-lighting#345]
#### Description:
I have Zigbee bulbs, and have defined an `Office Light Fixture` containing 4 bulbs using the ZHA integration's `Groups` feature.

After sunset/before sunrise if I walk into the office, I only want one single bulb to turn on dimly to provide just enough light to see by, so I have a "night light" automation to turn on just one bulb:
```YAML
- id: '1642161608570'
  alias: Office lights on when occupied - night light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.office_sensor_motion_aq2_ias_zone
    to: 'on'
    from: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
      before_offset: '30:00'
    - condition: sun
      after: sunset
      after_offset: '-30:00'
  action:
  - service: adaptive_lighting.set_manual_control
    data:
      entity_id: light.office_light_fixture
      manual_control: true
  - service: light.turn_on
    target:
      entity_id: light.office_bulb_1
    data:
      transition: 30
      kelvin: 2700
      brightness: 1
  mode: single
```

This works great so long as I do _not_ have any of the 4 office bulbs or the office light group configured to be controlled by AL. As soon as I add them to the AL config, all 4 bulbs will turn on at whatever the AL configured brightness level is, which is always too bright first thing in the morning...
