### ISSUE TITLE
Turning off Sleep Mode clears manual_control

### ISSUE THREAD

**Issue by ejpenney** [basnijholt/adaptive-lighting#346]
#### Version information:
Adaptive Lighting: 1.1.0
Home Assistant: 2022.10.0

#### Description:
Disabling Sleep Mode clears the manual_control attribute.  I don't think this is expected behavior.

Steps to reproduce:
1. Turn on target light
```
service: light.turn_on
  entity_id: light.family_room
```
2. Enable Sleep Mode
```
service: switch.turn_on
  entity_id: switch.adaptive_lighting_sleep_mode_family_room
```
3. Run adaptive_lighting.manual_control
```
service: adaptive_lighting.manual_control
  data:
    entity_id: switch.adaptive_lighting_family_room
    lights: light.family_room_overhead
    manual_control: True
```
4. Disable Sleep Mode
```
service: switch.turn_off
  entity_id: switch.adaptive_lighting_sleep_mode_family_room
```

Expected result: Since manual_control is set for light.family_room_overhead it should remain in its current state and manual_control should retain the value ['light.family_room_overhead']
Actual result: switch.adaptive_lighting_family_room attribute manual_control is cleared, and set to []

Let me know if there's anything else I can provide for this.
