### ISSUE TITLE
Can no longer use 2 switches for 1 set of lights

### ISSUE THREAD

**Issue by bouwew** [basnijholt/adaptive-lighting#35]
Hi Bas, great work on taking the Circadian component to a next level!

Now that I've switched to your component I've noticed that one of my "constructions" doesn't work anymore.
For my kitchen lights I had defined 2 sets of switches: one set for when someone is present in the kitchen, one set with lower brightness for when the kitchen is empty. With the Circadian component I could switch between these 2 sets instantly, most noticeable when entering the kitchen: the brightness-level of the lights would immediately increase.

Now that I use your component the script shown below no longer works.
```
turn_up_k_lights:
  sequence:
    - service: switch.turn_off
      entity_id:
        - switch.adaptive_lighting_adapt_color_keuken_dimmed
        - switch.adaptive_lighting_adapt_brightness_keuken_dimmed
    - service: switch.turn_on
      entity_id:
        - switch.adaptive_lighting_adapt_color_keuken
        - switch.adaptive_lighting_adapt_brightness_keuken
    - delay:
        milliseconds: 300
    - service: light.turn_on
      entity_id:
        - light.keuken_1
        - light.keuken_2
        - light.keuken_3
```

**Comment by basnijholt** [comment]
This is because when you are changing the `adapt_color` or `adapt_brightness` the lights aren't instantly updated.

This does happen when you toggle the switch.

This should work for you:
```yaml
turn_up_k_lights:
  sequence:
    - service: switch.turn_off
      entity_id: switch.adaptive_lighting_keuken_dimmed
    - service: switch.turn_on
      entity_id: switch.adaptive_lighting_keuken
    - delay:
        milliseconds: 300
    - service: light.turn_on
      entity_id:
        - light.keuken_1
        - light.keuken_2
        - light.keuken_3
```
