### ISSUE TITLE
send_split_delay invalid in config?

### ISSUE THREAD

**Issue by haseat** [basnijholt/adaptive-lighting#395]
#### Version information:
Home Assistant 2022.11.5
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest
Adaptive Lighting 1.2.1

#### Description:
I've had trouble some minor trouble with some IKEA GU10 lightbulbs, so I wanted to try out separate_turn_on_commands and send_split_delay. The first one works, but adding the latter to my config throws an error when trying to restart HA:

Config (snippet):
```
  - name: Bathroom Lights
    initial_transition: 0
    transition: 0
    sleep_transition: 0    
    separate_turn_on_commands: true
    send_split_delay: 100
    lights:
      - light.bathroom_lights 
```

Error:
`The system cannot restart because the configuration is not valid: Invalid config for [adaptive_lighting]: [send_split_delay] is an invalid option for [adaptive_lighting]. Check: adaptive_lighting->adaptive_lighting->1->send_split_delay. (See /config/configuration.yaml, line 216).
`
