### ISSUE TITLE
One light turning on again after turning off the group

### ISSUE THREAD

**Issue by Kurisudes** [basnijholt/adaptive-lighting#410]
#### Version information:
V1.4.1

#### Description:
On light turns back on again after turning off a group of zigbee lights (not a ZHA group but a group helper).

I get this if I listen to call_service:
Event 11 fired 9:58 AM:
event_type: call_service
data:
  domain: light
  service: turn_on
  service_data:
    entity_id: light.bedroom_light_bulb_1_level_light_color_on_off
    transition: 10
    brightness: 255
    color_temp_kelvin: 4000
origin: LOCAL
time_fired: "2022-12-22T08:58:36.535368+00:00"
context:
  id: adapt_lgt:b'*Xx`':interval:b'6%q'
  parent_id: null
  user_id: null

Event 9 fired 9:58 AM:
event_type: call_service
data:
  domain: light
  service: turn_off
  service_data:
    entity_id:
      - light.bedroom_light_bulb_1_level_light_color_on_off
      - light.bedroom_light_bulb_2_level_light_color_on_off
      - light.bedroom_light_bulb_3_level_light_color_on_off
origin: LOCAL
time_fired: "2022-12-22T08:58:31.689347+00:00"
context:
  id: 01GMWGWEBVZNCBWVF07F8S6AFR
  parent_id: 01GMWGWEBM53FTCQC1CPFV2ERG
  user_id: null

Event 8 fired 9:58 AM:

**Comment by matthiasradecke** [comment]
same is happening to me. random lights turn on back again after they are turned off by an automation. only happens sometimes. I already increased the update interval to 300 seconds and that makes it happen less often, but is still annoying to realize that the bedroom lights have been on for hours.

**Comment by matthiasradecke** [comment]
btw it does not happen when only_once is activated, which at least solved the problem for lights that don't stay on for long (like in the hallway). So it must be that the lights get updated with new values although they are already off (and state is showing off in HA)

**Comment by foulk466** [comment]
I have the same issue as mentioned above on version 1.4.1

Using an automation to turn off the lights, some of them turn on again (Not using groups, individual lights only)
If only_once activated it also fixes my issue.

History of the light that turn on again:

turned on triggered by service light.turn_on
2:31:16 PM - 2 minutes ago
turned off triggered by automation ****
triggered by state of Switch
2:30:54 PM - 3 minutes ago
turned on triggered by automation ****
triggered by state of Switch
2:29:22 PM - 4 minutes ago

**Comment by bluecube22** [comment]
Looks like a duplicate of https://github.com/basnijholt/adaptive-lighting/issues/377

In the Adaptive Lighting configuration, try setting `interval` to smaller value than `transition` and `sleep_transition` and restarting Home Assistant.

**Comment by nickdos** [comment]
I'm seeing this issue and I've tried the recommended settings from #377 but it did not fix anythingfor me. I've tried several variations, including using the exact values in the screenshot from that issue. 

My situation is specific to this issue, in that I'm experiencing this with Zigbee lights in a group. In my case the group is defined by the deCONZ system.

**Comment by th3w1zard1** [comment]
Can someone experiencing this on zigbee2mqtt post their configuration.yaml and devices.yaml so I can reproduce your settings?

**Comment by filikun** [comment]
I have had similar issues and for me it was the Z2M zigbee groups. Moving to HA groups removed the problem completely.

**Comment by filikun** [comment]
> Can someone experiencing this on zigbee2mqtt post their configuration.yaml and devices.yaml so I can reproduce your settings? Your adaptive-lighting config is also needed.
> 
> I was getting this issue with older configurations - using zigbee2mqtt. I was only able to solve this accidentally by updating everything to the latest version. I also redid the zigbee2mqtt configuration.yaml just to be certain everything would act the way I wanted it to. `optimistic` was very significant in my tests I remember.

I just tried reproducing it and got the issue right away. Here are my files.

[devices.zip](https://github.com/basnijholt/adaptive-lighting/files/11082598/devices.zip)

<details>
<summary>Pictures on the adaptive config</summary>
![image](https://user-images.githubusercontent.com/9947929/228055463-20eb54bd-5bf5-40af-84b8-073c0e137d86.png)

![image](https://user-images.githubusercontent.com/9947929/228055480-5976adec-2866-4e91-b222-d0875885a12f.png)
</details>

**Comment by th3w1zard1** [comment]
@filikun can you post debug logs of this happening? Set your interval low and you should notice the problem right away.
I use optimistic: true on my configuration: I couldn't get optimistic: false to work. When optimistic is false it would never publish any state changes to HA which adaptive-lighting relies on.

**Comment by filikun** [comment]
Yeah, I'll revert my optimistic change and turn on the logs. Give me a moment

**Comment by th3w1zard1** [comment]
Set your interval to something like 5 as well.

**Comment by filikun** [comment]
> 

Hmm how can I cahnge the interval?

**Comment by filikun** [comment]
Anyhow here is something. So I played around a little applying adaptive, taking it away, adding it again and applying night mode and turning on and off some individual lights. Not spamming them but a slow "stress" test and had some issues right away.

https://pastebin.com/u1xg9rsK

**Comment by th3w1zard1** [comment]
> > 
> 
> Hmm how can I cahnge the interval? And is there a way to isolate the logs from the logger integration? It's a lot going on here

Go to home assistant's integrations page. Should look like this:
![image](https://user-images.githubusercontent.com/2219836/228062370-41bdd856-b141-4581-b9ee-f9f4673a2764.png)

Click adaptive-lighting to see the following:
![image](https://user-images.githubusercontent.com/2219836/228062576-36f57ae8-98b3-403e-be0b-a81dad362431.png)

**Comment by filikun** [comment]
@th3w1zard1 

Alright! Here we go https://pastebin.com/5NQZRMfK

**Comment by filikun** [comment]
@th3w1zard1  

Did you find anything useful?

**Comment by th3w1zard1** [comment]
@filikun Sorry for the delay, haven't had much time to look into this.

For reference I see your group is composed of the following:

```
Lampa sovrum fönster 4
Lampa sovrum säng Filip 16
Lampa sovrum säng Hannah 17
Lampa sovrum skrivbord Filip 1
Lampa sovrum skrivbord Hannah 2
Lampa sovrum tak 6
```

Do you know if it's always the same bulb in the group everytime that is getting turned on?

I wasn't able to find anything useful in your logs, but there's a lot in there and I haven't had time to properly go line by line.


Is there perhaps anything useful in your logbook?
![image](https://user-images.githubusercontent.com/2219836/228942207-f627a5d8-ca0d-459b-89fe-a189884e3a02.png)

I have one more idea on how to test this but I'll need some time to write the automation.

**Comment by th3w1zard1** [comment]
@filikun I'm sorry I just need more information. I've created a script with the exact light.turn_on calls adaptive lighting is using from your posted logs. Can you run this script with your same group and see if you get the same issue? Make sure to turn off adaptive-lighting or disable it before running this.

```yaml
alias: Stress test zigbee group
sequence:
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 144
      color_temp_kelvin: 2500
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 144
      color_temp_kelvin: 2500
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 144
      color_temp_kelvin: 2500
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
mode: single
```

For the record I tried this on two different zigbee light groups I have and it worked fine.
