### ISSUE TITLE
Adaptive lighting based on sensor instead of sun

### ISSUE THREAD

**Issue by zebraelch** [basnijholt/adaptive-lighting#412]
Hi, I find the sunrise/set source not very accurate for having adaptive lighting. Sometimes it's very dark outside even after sunrise, or way before sunset, I would love the ability to have an alternative source to adapt to, and also be able to control the adaptivity curve somehow.

Thank you for your awesome plugin!

**Comment by alex3305** [comment]
I want to add my 2 cents to this. Until this is implemented within this great integration, I've created an automation that works similarly.

```yaml
- id: adaptive_lighting_office
  alias: Adaptive lighting - Office
  mode: restart
  variables:
    illuminance_entity: 'sensor.light_sensors_illuminance_max_average_1_hour'
    continuous_adjustment: true

    minimal_illuminance: 5
    maximal_illuminance: 4000

    minimal_brightness: 10
    maximal_brightness: 128

    color_temp_adjustment: true
    minimal_color_temp: 350
    maximal_color_temp: 250
  trigger:
    - platform: state
      entity_id: light.office
      from: 'off'
      to: 'on'
    - platform: homeassistant
      event: start
  condition:
    - condition: state
      entity_id: light.office
      state: 'on'
  action:
    repeat:
      sequence:
        - service: light.turn_on
          target:
            entity_id: light.office
          data:
            brightness: >-
              {% set illuminance  = states(illuminance_entity) | int(0) %}
              {% set input_start  = minimal_illuminance | int(0) %}
              {% set input_end    = maximal_illuminance | int(0) %}
              {% set output_start = minimal_brightness | int(0) %}
              {% set output_end   = maximal_brightness | int(0) %}

              {{ [[(illuminance - input_start) / (input_end - input_start) * (output_end - output_start) + output_start, output_end] | min, output_start] | max }}
            # Inspired from: https://community.home-assistant.io/t/template-entity-to-guess-the-outside-colour-temperature/402510
            color_temp: >-
              {% if (color_temp_adjustment | default(false)) %}
                {{ [ [ (1000000/(4791.67 - 3290.66/(1 + 0.222 * [ [ 0, state_attr('sun.sun', 'elevation') ] | max, 90 ] | min**0.81)))|int, (maximal_color_temp|int(0)) ] | max, (minimal_color_temp|int(0)) ] | min }}
              {% else %}
                {{ state_attr('light.office', color_temp) }}
              {% endif %}
            transition: "{{ (iif(repeat.first, 1, 3) | int(0)) }}"
        - wait_for_trigger:
            - platform: state
              entity_id: sensor.light_sensors_illuminance_max_average_1_hour
            - platform: state
              entity_id: light.office
              to: 'off'
          timeout:
            minutes: 15
          continue_on_timeout: true
        - delay:
            minutes: 1
      until:
        or:
          - condition: template
            value_template: "{{ (continuous_adjustment | default(false)) == false }}"
          - condition: template
            value_template: "{{ (states(illuminance_entity) | int(0)) <= (minimal_illuminance | int(0)) }}"
          - condition: state
            entity_id: light.office
            state: 'off'
          - condition: state
            entity_id: light.office
            state: 'unavailable'
            for:
              minutes: 1
```

This is not as good or efficient as this integration, but IMHO this is a start. And can be useful for someone who encounters this issue.

I also tried converting the automation above into a Blueprint, but it seems HA handles those a little differently. Because I had a massive memory leak last time I tried it.
