### ISSUE TITLE
[Feature Request] Output Manual Control Mode as Boolean

### ISSUE THREAD

**Issue by CM000n** [basnijholt/adaptive-lighting#42]
First of all, thank you very much for your great work. Adaptive Lighting is really great and has already completely replaced Circadian Lighting

Now to my problem. I have some automations that I would like to set up on the manual control state of my Adaptive Lighting. Unfortunately I don't get state not extrahier. I tried it with this Binary Sensor for example:

```yml
  - platform: template
    sensors:
      adaptive_lighting_buro_deckenlampe_manual_control:
        friendly_name: "Adaptive Lighting Büro Deckenlampe im manuellen Modus"
        value_template: >-
          {{ is_state_attr('switch.adaptive_lighting_buro_deckenlampe', 'manual_control', 'light.buro_deckenlampe') }}
```

Unfortunately it always shows off. No matter what the manual_control value of the switch is. 
So I would like to ask if it would be possible to output the manual control state as boolean on/off or as a separate sensor?

No matter what the answer is, thanks again for the great work and stay healthy ;-)

**Comment by peexl** [comment]
Hello,

The manual_control attribute return a list not a string your code should be : 

```yaml
  - platform: template
    sensors:
      adaptive_lighting_buro_deckenlampe_manual_control:
        friendly_name: "Adaptive Lighting Büro Deckenlampe im manuellen Modus"
        value_template: >-
          {{ is_state_attr('switch.adaptive_lighting_buro_deckenlampe', 'manual_control', ['light.buro_deckenlampe']) }}
 ```
if you have more than one light in your switch it's better to do this:
```yaml
  - platform: template
    sensors:
      adaptive_lighting_buro_deckenlampe_manual_control:
        friendly_name: "Adaptive Lighting Büro Deckenlampe im manuellen Modus"
        value_template: >-
          {{ 'light.buro_deckenlampe' in state_attr('switch.adaptive_lighting_buro_deckenlampe', 'manual_control') }}
 ```
