### ISSUE TITLE
Color_temp not going to warmest when using zigbee groups

### ISSUE THREAD

**Issue by bruvv** [basnijholt/adaptive-lighting#424]
#### Version information:
1.4.1

#### Description:
I noticed when using lights in a zigbee group (using zigbee2mqtt + home assistant (in HAOS)) lights do not turn warm all the way (color_temp: 500)
When adaptive lighting is adjusting the light group, it stops at color_temp: `454` with the following settings:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/3063928/215865034-2ad849e7-5394-4ccf-96ee-83600e9f1184.png">

When selecting individual lights they do go to a color_temp of `500`.

My zigbee group:
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/3063928/215866412-49e40c6a-dc37-41ac-a114-cebec5a3231c.png">

Why zigbee groups?
In a Zigbee network, a group is a collection of endpoints, such as multiple lightbulbs. Zigbee uses group addressing to communicate with groups of endpoints belonging to a set of devices. Groups aren’t just there to group certain lights, which might be in a single light fixture in the UI. They can actually be used to reduce Zigbee traffic.

That all might sound a bit complicated, but the gist of it is that using only one command has to be sent to the group instead of one command to each endpoint. Let’s say you have a light fixture which houses three Philips Hue spotlights. If you group the three lights, only one command is needed to turn on the whole light fixture. If you don’t group the lights, three commands are needed to turn on the fixture. By grouping the lights in this example, we’re only using a third of the commands that would otherwise be needed.

It is worth noting that Zigbee groups have nothing to do [Light Groups in Home Assistant](https://www.home-assistant.io/integrations/light.group/). Those are actually just for show and ease of use. Groups have to be configured in Zigbee2MQTT and not in Home Assistant.

**Comment by th3w1zard1** [comment]
We need you to post your `adaptive-lighting` config and debug messages sent out from the integration. See the readme on how to enable debug logging.

**Comment by bruvv** [comment]
Thanks @th3w1zard1 should have added that
Config:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/3063928/227168570-123740e8-fed5-42b9-a180-d634e780e651.png">

```
2023-03-23 23:34:06.705 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Woonkamer Spots: '_update_attrs_and_maybe_adapt_lights' called with context.id='adapt_lgt:b'C#}I':interval:b'{Q&''
2023-03-23 23:34:06.710 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: Woonkamer Spots: '_adapt_lights(['light.woonkamer_lampen'], 45.0, force=False, context.id=adapt_lgt:b'C#}I':interval:b'{Q&')' called
2023-03-23 23:34:06.713 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Slaapkamer: '_update_attrs_and_maybe_adapt_lights' called with context.id='adapt_lgt:b'Z+%)':interval:b'`~d''
2023-03-23 23:34:06.720 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: Slaapkamer: '_adapt_lights(['light.slaapkamer_lampen'], 45.0, force=False, context.id=adapt_lgt:b'Z+%)':interval:b'`~d')' called
2023-03-23 23:34:06.729 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Hal en gang: '_update_attrs_and_maybe_adapt_lights' called with context.id='adapt_lgt:b'm|j>':interval:b'1Of''
2023-03-23 23:34:06.735 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: Hal en gang: '_adapt_lights(['light.hal_lamp', 'light.voordeur_lamp'], 45.0, force=False, context.id=adapt_lgt:b'm|j>':interval:b'1Of')' called
2023-03-23 23:34:06.736 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Keuken: '_update_attrs_and_maybe_adapt_lights' called with context.id='adapt_lgt:b'mnNC':interval:b'0s;''
2023-03-23 23:34:06.748 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: Keuken: '_adapt_lights(['light.keuken_spots'], 45.0, force=False, context.id=adapt_lgt:b'mnNC':interval:b'0s;')' called
```

**Comment by th3w1zard1** [comment]
Can I see your zigbee config?
devices.yaml, configuration.yaml, and groups.yaml are all very important as I can use your exact config on my end to repro your problem.

**Comment by bruvv** [comment]
I updated my debug logs @th3w1zard1 here is my zigbee config:
```yaml
homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: *****
serial:
  port: /dev/ttyUSB0
  adapter: auto
  disable_led: true
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  transmit_power: 15
  channel: 25
  pan_id: 49768
  network_key: *
  log_level: warn
device_options:
  legacy: false
external_converters:
  - ds18b20_1.js
permit_join: false
devices:
  '0x0017880108cad459':
    friendly_name: keuken_lamp2
  '0x0017880108cac8d8':
    friendly_name: keuken_lamp1
  '0x0017880108d1bb9f':
    friendly_name: voordeur_lamp
  '0x0017880108cac8c8':
    friendly_name: woonkamer_lamp1
    color_sync: false
  '0x0017880108cac86b':
    friendly_name: woonkamer_lamp2
  '0x0017880108cad490':
    friendly_name: woonkamer_lamp4
  '0x0017880108cac886':
    friendly_name: woonkamer_lamp3
  '0x0017880108d1ba67':
    friendly_name: slaapkamer_lamp1
  '0x0017880108cac8a3':
    friendly_name: hal_lamp
  '0x0017880108cadf6a':
    friendly_name: slaapkamer_lamp2
  '0x00158d0003494c7e':
    friendly_name: keuken_motion
  '0x5c0272fffe24b7f7':
    friendly_name: afstandsbediening
  '0x00158d0001fa9bd5':
    friendly_name: woonkamer_temp
  '0x04cd15fffe5d4886':
    friendly_name: woonkamer_tafel_lamp
    color_sync: true
  '0x7cb03eaa0a0a76cb':
    friendly_name: hyperion
  '0x9035eafffe5aeb76':
    friendly_name: woonkamer_tv_lamp_rechts
  '0x04cf8cdf3c77ea79':
    friendly_name: tv_switch
  '0x9035eafffe4e242a':
    friendly_name: woonkamer_tv_lamp_links
    state_action: false
    color_sync: true
  '0x04cf8cdf3c7f2aec':
    friendly_name: woonkamer_lux
  '0x00158d0002bfed2d':
    friendly_name: voordeur
  '0x00158d0002bfe1d4':
    friendly_name: badkamerdeur
  '0x7cb03eaa0a09f111':
    friendly_name: badkamer_lamp
    homeassistant:
      switch:
        type: light
        object_id: light
      light:
        value_template: null
        state_value_template: '{{ value_json.state }}'
  '0x00158d0001e549a5':
    friendly_name: badkamer_temp
  '0x00158d0002349481':
    friendly_name: hal_motion
  '0x00158d0001ad454d':
    friendly_name: badkamer_motion
  '0x00158d0005bd2a63':
    friendly_name: slaapkamer_motion
  '0x04cd15fffea4f021':
    friendly_name: slaapkamer_bed_lamp
  '0x04cf8cdf3c77ed20':
    friendly_name: bedheater
  '0x847127fffe0ebcef':
    friendly_name: slaapkamer_verwarming_voor
  '0x00158d0003c4719f':
    friendly_name: hal_verwarming
    debounce: 0.5
    thermostat_unit: celsius
  '0x00158d00022880fa':
    friendly_name: slaapkamer_temp
  '0x847127fffe1f33ea':
    friendly_name: woonkamer_verwarming_rechts
  '0x00158d0003c3fc59':
    friendly_name: woonkamer_verwarming_links
    debounce: 0.5
    thermostat_unit: celsius
  '0x94deb8fffe2e6be1':
    friendly_name: badkamer_verwarming
  '0x94deb8fffe3c44a6':
    friendly_name: slaapkamer_verwarming_achter
  '0x04cf8cdf3c776fb1':
    friendly_name: office_switch
  '0x540f57fffe8971b4':
    friendly_name: afzuigkap
    homeassistant:
      switch:
        type: light
        object_id: light
      light:
        value_template: null
        state_value_template: '{{ value_json.state }}'
  '0x00124b0005a5a6c1':
    friendly_name: ista_groot
  '0x00124b000b1b754e':
    friendly_name: ista_klein
groups:
  '1':
    friendly_name: woonkamer_lampen
    transition: 2
    devices:
      - 0x0017880108cac8c8/11
      - 0x0017880108cac86b/11
      - 0x0017880108cac886/11
      - 0x0017880108cad490/11
      - 0x04cd15fffe5d4886/1
      - 0x9035eafffe4e242a/1
      - 0x9035eafffe5aeb76/1
  '2':
    friendly_name: slaapkamer_lampen
    transition: 2
    devices:
      - 0x04cd15fffea4f021/1
      - 0x0017880108d1ba67/11
      - 0x0017880108cadf6a/11
  '3':
    friendly_name: keuken_spots
    devices:
      - 0x0017880108cac8d8/11
      - 0x0017880108cad459/11
  '4':
    friendly_name: keuken_lampen
    devices:
      - 0x0017880108cac8d8/11
      - 0x0017880108cad459/11
      - 0x540f57fffe8971b4/1
  '5':
    friendly_name: woonkamer_spots
    devices:
      - 0x0017880108cac8c8/11
      - 0x0017880108cac86b/11
      - 0x0017880108cac886/11
      - 0x0017880108cad490/11
  '6':
    friendly_name: slaapkamer_spots
    devices:
      - 0x0017880108d1ba67/11
      - 0x0017880108cadf6a/11
availability: true
```
