### ISSUE TITLE
Tradfri Lights still adapted after a second light.turn_on

### ISSUE THREAD

**Issue by Jeltel** [basnijholt/adaptive-lighting#5]
- When turning on the lights for the first time with a script, the lights go to the set scene. And then after a short while AL will change the lights. This is logical.
- Then a second activation of the scripts, activates the lights and undoes what AL did.
- Then after a short while again, the Tradfri lights are updated by AL, while the Hue lights stay at the scene.

So AL recognizes that a scene has been set for the Hue lights, but not for the Tradfri lights.

This is what the script does:
```
woonkamer_energie:
  sequence:
  - data:
      entity_id: light.eettafel
      color_temp: 152
    service: light.turn_on
  - data:
      entity_id: light.koplamp
      color_temp: 152
    service: light.turn_on
  - data:
      brightness: 255
      entity_id: light.lamp_boven_zithoek
      color_temp: 152
    service: light.turn_on
  - data:
      brightness: 255
      entity_id: light.leeslamp_bank
      color_temp: 152
    service: light.turn_on
  - data:
      entity_id: light.lampjes_langs_het_plafond
    service: light.turn_on
  - delay:
      milliseconds: 1
  - data:
      brightness: 255
      entity_id: light.eettafel
    service: light.turn_on
  - data:
      brightness: 255
      entity_id: light.koplamp
    service: light.turn_on
  alias: Woonkamer Energie
```
Where light.eettafel and light.koplamp are Tradfri lights (bundles of 4 and 2 lights to be exact) and light.lamp_boven_zithoek and light.leeslamp_bank are HUE lights.
Thing with the Tradfri lights is that they cannot process two settings at the same time. So brightness and colour need to be set shortly after each other. So are actually already are two light.turn_on actions in this script.

**Comment by Jeltel** [comment]
@basnijholt what log do you need?
Which log setting do I need to set for home assistant?

**Comment by basnijholt** [comment]
Could you add this to your `configuration.yaml`:
```
logger:
  default: warning
  logs:
    custom_components.adaptive_lighting: debug
```
restart HA and share `home-assistant.log` after the problem occurred.
