### ISSUE TITLE
Some instances adapting, others are not

### ISSUE THREAD

**Issue by mg0716** [basnijholt/adaptive-lighting#53]
Hello! I seem to be having a slew of problems this morning, so apologies for the generic nature of the subject here. I’ll try to enumerate everything that’s going on. So far I have enabled logging but can’t seem to figure out where it’s spit out.

So as far as my current setup, here is my AL configuration:

```
- name: "Default"
  lights:
    - light.kitchen_cabinets
    - light.family_room_mantle
    - light.family_room_console
    - light.living_room_lamp
  min_brightness: 30
  take_over_control: true
  detect_non_ha_changes: true

- name: "Office"
  lights:
    - light.office_hue_play
    - light.office_ceiling_light
    - light.office_accent
  min_brightness: 30
  take_over_control: true
  detect_non_ha_changes: true

- name: "Bedroom"
  lights:
    - light.bedroom_nightstands
    - light.bedroom_bed_light
    - light.bedroom_dresser_lamp
  take_over_control: true
  detect_non_ha_changes: true

- name: "Landing"
  lights:
    - light.landing_ceiling_light
  take_over_control: true
  detect_non_ha_changes: true

- name: "Nash's Bedroom"
  lights:
    - light.nashs_dresser_lamp
```

Then here’s what I have in configuration.yaml:

```
logger:
  default: warning
  logs:
    homeassistant.components.homekit: debug
    custom_components.adaptive_lighting: debug

…

adaptive_lighting: !include adaptive-lighting.yaml
```
_Note: the `…` is not in the actual file._

A couple of unordered things from this morning:
- The `Default` lights do seem to be adapting the color just fine, but nothing else is adapting color right now (stuck at peak warmness). I checked and the color toggle does indeed seem to be set to `On` for those instances.
- Also note with the above: I know AL is in control, because when I toggle `Sleep` mode in the office, it does change the lights.
- The brightness on the lights in every instance were at nearly 80% even an hour before sunrise. The sun crossed over the horizon at 7:07am, and everything was 100% before that. Is that expected behavior?
- I’ve tried to set up for manual control as mentioned in your readme, but it too doesn’t seem to be working at all. Any thoughts?

```
alias: 'AL: On manual light change, reset Adaptive Lighting after 1 hour'
description: ''
trigger:
  - platform: event
    event_type: adaptive_lighting.manual_control
condition: []
action:
  - delay: '01:00:00'
  - condition: template
    value_template: '{{ light in state_attr(switch, ''manual_control'') }}'
  - service: adaptive_lighting.set_manual_control
    data:
      entity_id: '{{ switch }}'
      lights: '{{ light }}'
      manual_control: false
mode: parallel
variables:
  light: '{{ trigger.event.data.entity_id }}'
  switch: '{{ trigger.entity_id }}'
max: 10
```

Any help would be wonderful! And hopefully this is helpful to you as well.
