### ISSUE TITLE
Feature request - Cloudiness offset

### ISSUE THREAD

**Issue by proggprod** [basnijholt/adaptive-lighting#578]
I'm coming from another smarthome platform and am new to HA. 
I had something similar to this and something that was really nice was a 'Cloudiness Offset'. On dark cloudy days it makes the lights a little warmer.
The cloud factor can be taken from all kinds of sensors - local weather APIs, outdoor weather stations, solar panel readings, my Tado integration even had a solar percentage sensor.
It is important to add a max step to any change as some readings from things like local weather APIs can be very coarse, jumping from 25% to 75% instantly.

This worked well for me for calculating how much to reduce the temperature by. A setting of 50% works well for <user_defined_cloudiness_offset_factor> :

        cloudiness = <sensor.cloudiness_reading> * <user_defined_cloudiness_offset_factor>
        amount_to_reduce_by= (raw_calculated_kelvin_temperature - warmestTemp) * cloudiness

        final_calculated_kelvin_temperature = raw_calculated_kelvin_temperature - amount_to_reduce_by

round up  to min temperature to prevent value going below minimum

![image](https://user-images.githubusercontent.com/81530084/233033589-014c8551-557d-4e71-b1cb-32b3db310111.png)

**Comment by basnijholt** [comment]
This can be implemented using a simple automation.

Just use the `adaptive_lighting.change_switch_settings` ( https://github.com/basnijholt/adaptive-lighting#adaptive_lightingchange_switch_settings) and adjust your `max_color_temp` accordingly.

Will close this issue because a solution exists. Thanks for your suggestion though!

**Comment by basnijholt** [comment]
From my reply here https://github.com/basnijholt/adaptive-lighting/issues/122#issuecomment-1666968584

You can utilize a linear equation to adjust the `max_brightness` continuously based on the brightness sensor's reading. Here's a sample automation that linearly scales the `max_brightness` based on the readings of the `sensor.brightness`:

```yaml
automation:
  - alias: "Adjust Adaptive Lighting Brightness based on Brightness Sensor"
    trigger:
      platform: state
      entity_id: sensor.brightness
    action:
      - service: adaptive_lighting.change_switch_settings
        data_template:
          max_brightness: >
            {% set sensor_val = states('sensor.brightness')|int %}
            {% set max_brightness = 100 - sensor_val %}
            {{ [1, max_brightness, 100]|sort()[1] }}
```

Explanation:

- The automation triggers every time the state of `sensor.brightness` changes.
- The linear equation used is \( \text{max\_brightness} = 100 - \text{sensor\_value} \). This means when the brightness sensor reads a value of 0, the maximum brightness will be 100, and when the brightness sensor reads a value of 100, the maximum brightness will be 0.
- The template at the end ensures that the value stays between 1 and 100.
