### ISSUE TITLE
Sensor to read calculated values

### ISSUE THREAD

**Issue by LukeDefeo** [basnijholt/adaptive-lighting#61]
Hello

It would be really nice of there was a sensor or some other entity in HA which could tell me the current caclulated brightness / colour temp for a switch.

My use case is i have some scenes that i want to continuously update that use the correct values for brightness and colour temp, this is to avoid the shift after it comes on.

**Comment by ekeih** [comment]
The switch `switch.adaptive_lightning_FOO` has the calculated values as attributes. It should be possible to use these instead of an additional sensor. (You could also create a template sensor to expose the attributes as separate sensors if you like.)

```
brightness_pct: 1
color_temp_kelvin: 1000
color_temp_mired: 1000
rgb_color: 255, 67.92041905680745, 0
xy_color: 0.673, 0.322
hs_color: 16.016, 98.431
sun_position: -0.5320782503193084
manual_control:
friendly_name: FOO
icon: mdi:theme-light-dark
```

**Comment by basnijholt** [comment]
You could add template sensors like I did [here](https://github.com/basnijholt/home-assistant-config/blob/9fdffc531ece4d753ae1924437632bfa3c4cbdd9/includes/sensors.yaml#L258-L276).

Then either plot it using Grafana or using this card (download the custom cards first):
```
cards:
  - color_thresholds_transition: smooth
    entities:
      - entity: sensor.adaptive_lighting_brightness
        name: Brightness
        show_state: true
      - entity: sensor.adaptive_lighting_color_temp_kelvin
        name: Color temp (Kelvin)
        show_state: true
        y_axis: secondary
    font_size: 80
    group: false
    name: Brightness vs color temp
    hours_to_show: 72
    hour24: true
    line_width: 2
    points_per_hour: 2
    lower_bound: 60
    upper_bound: 105
    lower_bound_secondary: 0
    upper_bound_secondary: ~5500
    show:
      extrema: false
      fill: fade
      labels: false
      name: true
      state: true
    type: 'custom:mini-graph-card'
  - color_thresholds_transition: smooth
    entities:
      - entity: sensor.adaptive_lighting_brightness
        name: Brightness
        show_state: true
      - entity: sensor.adaptive_lighting_sun_position
        name: Sun position
        show_state: true
        y_axis: secondary
    font_size: 80
    group: false
    name: Brightness vs sun position
    hours_to_show: 72
    hour24: true
    line_width: 2
    points_per_hour: 2
    lower_bound: 40
    upper_bound: 100
    lower_bound_secondary: -100
    upper_bound_secondary: 100
    show:
      extrema: false
      fill: fade
      labels: false
      name: true
      state: true
    type: 'custom:mini-graph-card'
  - color_thresholds_transition: smooth
    entities:
      - entity: sensor.adaptive_lighting_color_temp_kelvin
        name: Color temp
        show_state: true
      - entity: sensor.adaptive_lighting_sun_position
        name: Sun position
        show_state: true
        y_axis: secondary
    font_size: 80
    group: false
    hours_to_show: 72
    hour24: true
    name: Color temp vs sun position
    line_width: 2
    points_per_hour: 2
    lower_bound: 0
    upper_bound: ~5500
    lower_bound_secondary: -100
    upper_bound_secondary: 100
    show:
      extrema: false
      fill: fade
      labels: false
      name: true
      state: true
    type: 'custom:mini-graph-card'
type: 'custom:swipe-card'
```
Result:
![card|250x123](https://community-assets.home-assistant.io/original/3X/8/6/86ec5e6b27d876e46eeed96e1b3f317e8535f7f8.gif)
