### ISSUE TITLE
Sleep mode turn off lights

### ISSUE THREAD

**Issue by Just-Insane** [basnijholt/adaptive-lighting#71]
Hello,

I am wondering if it is possible to have sleep mode turn the lights off. I tried setting the value to 0 but it gives an error.

Is there an example for setting manual mode on and turning lights off when turning sleep mode on?

**Comment by haseat** [comment]
Having an option to automatically turn off the lights when sleepmode is activated would actually be awesome.

**Comment by basnijholt** [comment]
This is accomplished extremely easily by using an automation.

Something like
yaml
```
- alias: "Turn off light when turning on sleep mode"
  trigger:
    platform: state
    entity_id: switch.adaptive_lighting_default_sleep_mode
    to: "on"
  action:
    service: light.turn_off
    entity_id:
      - light.light1
      - light.light2
```

Therefore I do not think I will add this option.

Perhaps I can add an attribute to the switch "lights" which is a list of the lights that the instance contains. Then you can template the `entity_id` in the `light.turn_off` action.
