### ISSUE TITLE
Move Prefer RGB to switch from configuration

### ISSUE THREAD

**Issue by broyuken** [basnijholt/adaptive-lighting#74]
Looking to do something similar to https://github.com/basnijholt/adaptive-lighting/issues/36. Could you please consider moving the prefer rgb over color temp out of the configuration and into a switch? That way I could toggle it off and on along with my sleep mode. I have some bulbs that are too bright even at 1% when using color temp but when I use rgb they can go nice and low. I like the color temps during the day but would like my "night light" to be super dim by changing from color temp to rgb.

**Comment by broyuken** [comment]
I have attempted to use the following service call, and the prefer_rgb_color works. But only until the light checks in again, then it goes back to false. How do I make this change permanent, or at least until I turn the switch off and on again? 

```
service: adaptive_lighting.apply
data:
  entity_id: switch.adaptive_lighting_sylvania_bulbs
  lights: light.office_lamp_floor
  prefer_rgb_color: true
```
