### ISSUE TITLE
Feature request: Color temp override

### ISSUE THREAD

**Issue by sgofferj** [basnijholt/adaptive-lighting#795]
I'd like to suggest

## Color temp override
```yaml
service.adaptive_lighting.set_color_temperature
data:
  entity_id: [AL entity]
  color_temperature: [color temperature in Kelvin]

```
Use case examples:
- You want cold light because you have to work late and coffee would keep you from sleeping later
- It's early evening, it's dark outside because of thick clouds and you want to wind down early
