### ISSUE TITLE
Readapt After Power Loss (Hard Off and On)

### ISSUE THREAD

**Issue by banter7702** [basnijholt/adaptive-lighting#824]
Hi,

I observed that when I take back control say change color, then simulate power loss, then power comes back on, of course the light will turn back to its last state thru its firmware.

However, I expect it to readapt, just like softly turning the rgb light off and on.

I need this because my light is tied to a switch, and both are in home assistant. I have this habit to turn the light off thru the switch (this simulate power loss for the rgb light) instead of the remote of the rgb light.

My current settings are:
Take over control: enabled
Detect non ha changes: enabled (enabled or disabled doesnt make any difference to my issue).

Everything else is default.

**Comment by 4D4M-Github** [comment]
I have tried to avoid this in two ways so far:

1. When the disconnected lamp is logged in again on mqtt, I send an "Adaptive Lighting: apply" service command via automation, but unfortunately I noticed that it ignores the "adapt_brightness" and "adapt_color" settings and the AL switch settings and ALWAYS applies ALL parameters. Is this otherwise normal operation?
2. When the disconnected lamp is logged back on mqtt, I send a "turn: on" command from Home Assistant. At this time, I check the status of adapt_color and adapt_brightness switches in automation instead.

In the longer term, I would like to avoid using the dumb switches and replace them with something smarter, but in the meantime it would be better if AL handled this situation.

**Comment by bjornsivertsen** [comment]
> I have tried to avoid this in two ways so far:
> 
> 1. When the disconnected lamp is logged in again on mqtt, I send an "Adaptive Lighting: apply" service command via automation, but unfortunately I noticed that it ignores the "adapt_brightness" and "adapt_color" settings and the AL switch settings and ALWAYS applies ALL parameters. Is this otherwise normal operation?
> 2. When the disconnected lamp is logged back on mqtt, I send a "turn: on" command from Home Assistant. At this time, I check the status of adapt_color and adapt_brightness switches in automation instead.
> 
> In the longer term, I would like to avoid using the dumb switches and replace them with something smarter, but in the meantime it would be better if AL handled this situation.

Hi 4D4M Could you share how you achieved this?

**Comment by bjornsivertsen** [comment]
> I have tried to avoid this in two ways so far:
> 
> 1. When the disconnected lamp is logged in again on mqtt, I send an "Adaptive Lighting: apply" service command via automation, but unfortunately I noticed that it ignores the "adapt_brightness" and "adapt_color" settings and the AL switch settings and ALWAYS applies ALL parameters. Is this otherwise normal operation?
> 2. When the disconnected lamp is logged back on mqtt, I send a "turn: on" command from Home Assistant. At this time, I check the status of adapt_color and adapt_brightness switches in automation instead.
> 
> In the longer term, I would like to avoid using the dumb switches and replace them with something smarter, but in the meantime it would be better if AL handled this situation.

Hi @4D4M-Github Could you share how you achieved this?

**Comment by 4D4M-Github** [comment]
> Hi @4D4M-Github Could you share how you achieved this?

@bjornsivertsen Which point are you wondering about exactly?

This is the event I catch in automation:
```
trigger:
  - platform: state
    entity_id:
      - light.some.entity
    from: unavailable
    to: "on"
```

**Comment by bjornsivertsen** [comment]
Hey @4D4M-Github, that was incredibly simple. I feel a bit stupid now, I was thinking you were listening to MQTT topics or something.

Do you have an automation per light, or is there a smart way to target them from one automation.

**Comment by 4D4M-Github** [comment]
> Do you have an automation per light, or is there a smart way to target them from one automation.

@bjornsivertsen I've bundled them into an automation and you can use the "choose" option to select them based on the id you specify in the trigger. Something like this:

```
trigger:
  - platform: state
    entity_id:
      - light.some.entity1
    from: unavailable
    to: "on"
    id: THIS IS THE ID1
  - platform: state
    entity_id:
      - light.some.entity2
    from: unavailable
    to: "on"
    id: THIS IS THE ID2
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - THIS IS THE ID1
        sequence:
          - if:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: switch.adaptive_lighting_some.entity1
                    state: "on"
                  - condition: state
                    entity_id: switch.adaptive_lighting_adapt_color_some.entity1
                    state: "on"
            then:
              - service: switch.turn_off
                target:
                  entity_id:
                    - switch.adaptive_lighting_some.entity1
                data: {}
              - service: switch.turn_on
                metadata: {}
                data: {}
                target:
                  entity_id: switch.adaptive_lighting_some.entity1
      - conditions:
          - condition: trigger
            id:
              - THIS IS THE ID2
        sequence:
          - if:
              - condition: and
                conditions:
                  - condition: state
                    entity_id: switch.adaptive_lighting_some.entity2
                    state: "on"
                  - condition: state
                    entity_id: switch.adaptive_lighting_adapt_color_some.entity2
                    state: "on"
            then:
              - service: switch.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id: switch.adaptive_lighting_some.entity2
              - service: switch.turn_on
                target:
                  entity_id:
                    - switch.adaptive_lighting_some.entity2
                data: {}
```
Of course, it would be much more elegant if AL's "apply" feature worked (:
