### ISSUE TITLE
Add an option to use night mode of lights in sleep mode

### ISSUE THREAD

**Issue by JonathanKang** [basnijholt/adaptive-lighting#836]
Currently an option is available to set the brightness percentage in sleep mode, which is good. The [ceiling lights](https://home.miot-spec.com/spec/pmfbj.light.xsx341) at my home provides a night mode which is dimmer than 1% brightness. When `night` mode is on, the brightness percentage is still 1%. But it is significantly dimmer.

So is it possible to add an option to enable this night mode when sleep mode is on?

The `Night` mode can be turn on with the following service.
```
service: light.turn_on
data:
  effect: Night
target:
  entity_id: light.ceiling_light
```
