### ISSUE TITLE
Take Over Brightness Option

### ISSUE THREAD

**Issue by zpriddy** [basnijholt/adaptive-lighting#889]
A friend and I have the same issue.. 

sometimes we want to make it darker or brighter in the room that we are in and have it stay at the set brightness.. however we would like AL to keep adapting the color of the lights, but not the brightness.. 

This can be achieved by looking for manual events where the brightness is set.. and switch off the AL Adapt Brightness switch.. but this is a big pain to do.. 

Would it be possible to have an option like Take Over Control - but only prevents AL from changing the brightness (or turns off the adapt brightness switch) if the brightness is manually controlled? 

kinda in the same topic but can be a different request.. it would be nice if there was a manual control switch , or if when taking over control (existing) it turns off the adaptive lighting switch..  it’s kinda hard to know when you are still taking over control.. but like I said a different request.. but it would be nice for take over brightness to use that kind of logic ..

**Comment by basnijholt** [comment]
There is a switch you will have to do what you want, see the 3rd and 4th points here https://github.com/basnijholt/adaptive-lighting?tab=readme-ov-file#bulb-features

**Comment by zpriddy** [comment]
It would be two automations per zone, looking for turn on events with brightness, across 7 zones.. it ends up being a lot to add in.. but it AL is already listing to events to figure out if manual control is overriding the AL, it seems like I could be a check added into AL without much overhead.. I think there would be a large benefit to many to have this feature implemented.. but that is just my opinion.

**Comment by HAkegel** [comment]
I Agree with zpriddy. Most people don't change the color temperatures of there lamps manually. Having a checkbox with 'Keep colortemperature synced' would be an awesome feature.

**Comment by zpriddy** [comment]
I was trying to setup some automation for this.. However the only solution would be to trigger off of every `state_changed` event or any. state change event from every adaptive lighting switch. Then add a condition to the automation to see if there are any lights in the manual control config.. and if there are.. then set the color temp to the value in the trigger event/switch value using the transition period in the event.. 

However that is a LOT of events that get sent depending on the number and configuration of your AL setup.. Im not quite sure its very feasible to take that approach.. At the very least its a lot of automation triggers to be running..

**Comment by dusanjencik** [comment]
Hi, I join the group who would appreciate the independence of brightness and color temperature adaptivity. For now I use this set up as a workaround, hopefully it will help others as an idea.

**Goal**
- Adapt brightness for each room/light group separately.
- When the brightness is changed (for example a scene is set), disable adapting brightness, however continue with adapting the color temperature.
- Adapt color temperature regardless the brightness settings.
- Have the same color temperature in the whole house at the time.

**Set up**
- I have a new Entry for every room/light group (like hallway, kitchen spotlights, kitchen dinner table...). In this instance I define the main settings for the brightness adaptation behaviour.
I have checked `take_over_control`.
In the instance entities I disable Adapting Color switch.
- I have created a virtual light in configuration.yaml, for this I need 3 Helpers (input_number.virtual_light_brightness, input_number.virtual_light_color_temp, input_boolean.virtual_light_state).
```
light:
- platform: template
  lights:
    virtual_light:
      unique_id: "virtual_light"
      friendly_name: "Virtual light"
      value_template: "{{ states('input_boolean.virtual_light_state') }}"
      level_template: "{{ states('input_number.virtual_light_brightness') | int }}"
      temperature_template: "{{ states('input_number.virtual_light_color_temp') | int }}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.virtual_light_state
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.virtual_light_state
      set_level:
        service: input_number.set_value
        target:
          entity_id: input_number.virtual_light_brightness
        data_template:
          value: "{{ brightness }}"
      set_temperature:
        service: input_number.set_value
        target:
          entity_id: input_number.virtual_light_color_temp
        data_template:
          value: "{{ color_temp }}"
```
- And I have created a new instance of Adaptive Lighting for that Virtual light where I set up the default behaviour for the color temperature adaptation. **The great benefit is, that it can be different to the brightness settings of other instances.**
Also, the brightness entity switch might be disabled to have no updates with any effect.
- I keep turned on the Virtual light. In its parameters, the adapted values are hold. I am interested especially in `color_temp`.
- I have a new automation to update the `color_temp` of any light when turned on, or when Virtual light `color_temp` has changed.
```
alias: "Update color temp by Virtual light"
description: ""
trigger:
  - platform: state
    entity_id:
      - light.virtual_light
    attribute: color_temp_kelvin
    id: Color update
  - platform: state
    entity_id:
      - light.kitchen_dinner_table_light_1
      - light.kitchen_dinner_table_light_2
      - light.kitchen_dinner_table_light_3
      - light.kitchen_dinner_table_light_4
      - light.kitchen_spot_light_1
      - .... // define your list of all lights. It's needed to keep it descriptive here, otherwise you would need to listen to all events which might be too crazy.
    from: "off"
    to: "on"
    id: Some light is turned on
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - Color update
        sequence:
          - service: script.set_color_if_lights_on
            data:
              kelvin: "{{ state_attr('light.virtual_light', 'color_temp_kelvin') }}"
              entity_ids:
                - light.kitchen_dinner_table_light_1
                - light.kitchen_dinner_table_light_2
                - light.kitchen_dinner_table_light_3
                - light.kitchen_dinner_table_light_4
                - light.kitchen_spot_light_1
                - ... // define your list of all lights
      - conditions:
          - condition: trigger
            id:
              - Some light is turned on
        sequence:
          - service: script.set_color_if_lights_on
            data:
              kelvin: "{{ state_attr('light.virtual_light', 'color_temp_kelvin') }}"
              entity_ids: "{{ trigger.entity_id }}"
            enabled: true
mode: queued
max: 10
```
- For the updating only turned on lights I use this script:
```
alias: Set Color if Lights On
sequence:
  - variables:
      kelvin: "{{ kelvin }}"
      light_entities: "{{ entity_ids }}"
      entities_to_regulate: >
        {{ expand(light_entities) | selectattr('state', 'eq', 'on') |
        map(attribute='entity_id') | list }}
  - condition: template
    value_template: "{{ entities_to_regulate | count > 0 }}"
  - service: light.turn_on
    data_template:
      entity_id: "{{ entities_to_regulate | join(', ') }}"
    data:
      kelvin: "{{ kelvin }}"
mode: restart
```
- To have a correct behaviour when setting a scene, I need manually update the scene definition in scenes.yaml to omit all the color change definitions. I keep there only brightness definitions. Otherwise the scene would change the color to something pre-defined and in x seconds (default is 90 in Adaptive lighting) the color will be changed back to the Virtual light color temperature which is annoying.

**Know limitations**
- The only limitation I observe is that during the night, when the color temperature of Virtual light is set to the minimum, there is no update of the `color_temp`, which causes no update of the manually changed color of any light back to the correct Virtual light value.
