### ISSUE TITLE
Lights controlled as group are not marked as manually controlled

### ISSUE THREAD

**Issue by atomicus** [basnijholt/adaptive-lighting#945]
# Home Assistant Adaptive Lighting Issue Template

## Bug Reports

If you need help with using or configuring Adaptive Lighting, please [open a Q&A discussion thread here](https://github.com/basnijholt/adaptive-lighting/discussions/new?category=q-a) instead.

### Before submitting a bug report, please follow these troubleshooting steps:

Please confirm that you have completed the following steps:

- [x] I have updated to the [latest Adaptive Lighting version](https://github.com/basnijholt/adaptive-lighting/releases) available in [HACS](https://hacs.xyz/).
- [x] I have reviewed the [Troubleshooting Section](https://github.com/basnijholt/adaptive-lighting#troubleshooting) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] (If using Zigbee2MQTT) I have read the [Zigbee2MQTT troubleshooting guide](https://github.com/basnijholt/adaptive-lighting#zigbee2mqtt) in the [README](https://github.com/basnijholt/adaptive-lighting#readme).
- [x] I have checked the [V2 Roadmap](https://github.com/basnijholt/adaptive-lighting/discussions/291) and [open issues](https://github.com/basnijholt/adaptive-lighting/issues) to ensure my issue isn't a duplicate.

### Required information for bug reports:

Please include the following information in your issue.

*Issues missing this information may not be addressed.*

1.  **Debug logs** captured while the issue occurred. [See here for instructions on enabling debug logging](https://github.com/basnijholt/adaptive-lighting#troubleshooting):

```
```

2.  [Your Adaptive Lighting configuration](https://github.com/basnijholt/adaptive-lighting#gear-configuration):

adaptive_lighting:
```
  - name: "Bedroom"
    lights: [light.bedroom_ambient, light.bedroom_ambient_2]
    prefer_rgb_color: true
    initial_transition: 10
    transition: 0
    sunrise_time: "07:30:00"
    sunset_time: "20:00:00"
```

```

```

4.  Describe the bug and how to reproduce it:

AL stoped marking lights as manually controlled when light is controlled by a group (HA group, not zigbee).

Following code tha reacts to my pilot:
```
- alias: Ikea remote
  id: "1499"
  description: ""
  use_blueprint:
    path: ikea_remote.yaml
    input:
      remote: sensor.pilot_1_action
      button_on:
        - type: brightness_increase
          device_id: e0f41cbd8d042797468be62c40b663cf
          entity_id: light.automatic
          domain: light
      button_off:
        - device_id: e0f41cbd8d042797468be62c40b663cf
          entity_id: light.bedroom_ambient
          type: brightness_decrease
          domain: light
      button_left_click:
        - service: input_boolean.toggle
          entity_id: input_boolean.night_enabled
```

1. Works: When buttton off is presed and a brightness is decreases only of a single light.
2. Doesn't work: When button on is pressed and brightness is increase for a group of lights (they go back to AL control after few seconds).

This is referenced in state of AL when manual control contains only lights changed directly, but does not include lights of group.

5. Steps to reproduce the behavior:

1. Add light (controlled by AL) to group
2. Set brightness to group manually. Light will come back to AL brightness after a while

I'm sure this was working before, but not sure in which version.
