### ISSUE TITLE
Add an option for turning the light off / on overnight, IE min brightness of 0%

### ISSUE THREAD

**Issue by edalquist** [basnijholt/adaptive-lighting#953]
I'm trying to use Adaptive Lighting on a grow light an would like it to be 100% automated with the light off for the period of time that Adaptive Lighting currently has it at 1%

**Comment by edalquist** [comment]
Yes in my case I want a "night time" scene that is all-off.


My current work-around is the following automation:


```
alias: "!Aquaponics On/Off"
description: ""
trigger:
  - platform: numeric_state
    entity_id:
      - switch.adaptive_lighting_aquaponics_lights
    attribute: brightness_pct
    above: 1.1
    id: ABOVE_ONE
  - platform: numeric_state
    entity_id:
      - switch.adaptive_lighting_aquaponics_lights
    attribute: brightness_pct
    below: 1.1
    id: BELOW_ONE
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - ABOVE_ONE
        sequence:
          - service: adaptive_lighting.apply
            data:
              turn_on_lights: true
              entity_id: switch.adaptive_lighting_aquaponics_lights
      - conditions:
          - condition: trigger
            id:
              - BELOW_ONE
        sequence:
          - service: light.turn_off
            target:
              device_id: 3441a492b67a496972f83ecee2323ea6
            data: {}
mode: single
```
